package cmd

import (
	"bufio"
	"context"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/mulgadc/spinifex/spinifex/admin"
	handlers_acm "github.com/mulgadc/spinifex/spinifex/handlers/acm"
	"github.com/mulgadc/spinifex/spinifex/utils"
	"github.com/spf13/cobra"
)

var certCreateTenantCACmd = &cobra.Command{
	Use:   "create-tenant-ca",
	Short: "Create the ACM tenant private CA for PRIVATE_CA certificate issuance",
	Long: `Creates the tenant root CA that ACM's PRIVATE_CA validation mode signs leaf
certificates from. This is a separate, independent root from the platform CA
(ca.pem/ca.key generated by 'spx admin init') — it is never used for node-to-node
trust, ipsec, or system VM guests, and installing it into device trust stores
is a one-time, per-deployment action.

--domain is required and repeatable. The domains given here are baked into the
CA as x509 name constraints and are frozen at creation: PRIVATE_CA certificate
requests are only honoured for these domains (and their subdomains), and
widening the list later requires regenerating the root.

Running this command against an already-existing tenant CA reports what is
already there rather than silently regenerating — rotating the root invalidates
every device's trust store at once, so that can only ever be an explicit,
operator-driven action via --regenerate.`,
	Run: runCertCreateTenantCA,
}

// certForceRenewCmd reissues a PRIVATE_CA certificate immediately, over NATS
// against the running daemon's renewal worker — distinct from certRenewCmd
// ("spx admin cert renew"), which regenerates the node's own server TLS
// certificate offline and is unrelated to ACM.
var certForceRenewCmd = &cobra.Command{
	Use:   "force-renew",
	Short: "Reissue an ACM PRIVATE_CA certificate immediately, bypassing its renewal window",
	Long: `Reissues the given ACM certificate under its existing ARN right now, instead of
waiting for the renewal worker's proportional window to elapse. Only PRIVATE_CA
certificates (tenant-CA-issued) can be force-renewed; imported and public
certificates are refused.

This talks to the running daemon over NATS, taking the same per-certificate
lease the scheduled renewal worker uses, so it is safe to run against a live
deployment. It exists primarily to verify the ELBv2 fan-out — that every load
balancer referencing the certificate re-renders with the new leaf — without
waiting out the real renewal window.`,
	Run: runCertForceRenew,
}

func init() {
	certCmd.AddCommand(certCreateTenantCACmd)
	certCreateTenantCACmd.Flags().StringSlice("domain", nil, "Domain the tenant CA is permitted to sign for (repeatable)")
	certCreateTenantCACmd.Flags().Bool("regenerate", false, "Replace an existing tenant CA with a fresh root (invalidates every device's trust store — requires confirmation)")
	certCreateTenantCACmd.Flags().Bool("yes", false, "Skip the --regenerate confirmation prompt")
	if err := certCreateTenantCACmd.MarkFlagRequired("domain"); err != nil {
		panic(err)
	}

	certCmd.AddCommand(certForceRenewCmd)
	certForceRenewCmd.Flags().String("arn", "", "Certificate ARN to force-renew (required)")
	certForceRenewCmd.Flags().String("account", "", "Account ID that owns the certificate; defaults to the bootstrap account")
	if err := certForceRenewCmd.MarkFlagRequired("arn"); err != nil {
		panic(err)
	}
}

func runCertForceRenew(cmd *cobra.Command, _ []string) {
	certArn, _ := cmd.Flags().GetString("arn")
	accountID, _ := cmd.Flags().GetString("account")
	if accountID == "" {
		accountID = admin.DefaultAccountID()
	}

	_, nc, err := loadConfigAndConnect()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
	defer nc.Close()

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	fmt.Printf("Force-renewing %s (account %s)...\n", certArn, accountID)
	out, err := utils.NATSRequest[handlers_acm.ForceRenewCertificateOutput](
		ctx, nc, "acm.ForceRenewCertificate",
		&handlers_acm.ForceRenewCertificateInput{CertificateArn: certArn},
		30*time.Second, accountID,
	)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Reissued %s\n", out.CertificateArn)
	fmt.Printf("  Serial:    %s\n", out.Serial)
	fmt.Printf("  NotAfter:  %s\n", out.NotAfter.Format(time.RFC3339))
}

func runCertCreateTenantCA(cmd *cobra.Command, _ []string) {
	domains, _ := cmd.Flags().GetStringSlice("domain")
	regenerate, _ := cmd.Flags().GetBool("regenerate")
	yes, _ := cmd.Flags().GetBool("yes")

	configDir, _ := cmd.Root().Flags().GetString("config-dir")
	certPath := admin.TenantCACertPath(configDir)
	keyPath := admin.TenantCAKeyPath(configDir)

	existed := admin.FileExists(certPath) && admin.FileExists(keyPath)

	if existed && regenerate {
		fmt.Println("⚠️  About to regenerate the tenant CA. This invalidates trust for every")
		fmt.Println("   device that has installed the current root — each one will need the new")
		fmt.Println("   certificate reinstalled before it trusts PRIVATE_CA leaves again.")
		fmt.Printf("   Current CA:      %s\n", certPath)
		fmt.Printf("   New domains:     %s\n", strings.Join(domains, ", "))
		fmt.Println()
		if !yes {
			fmt.Print("Type 'yes' to proceed: ")
			reader := bufio.NewReader(os.Stdin)
			answer, _ := reader.ReadString('\n')
			if strings.TrimSpace(answer) != "yes" {
				fmt.Println("Aborted.")
				return
			}
		}
		// Regeneration is a deliberate, explicit action only reachable via
		// --regenerate (plus confirmation) — LoadOrCreateTenantCA itself never
		// regenerates over an existing root, so the old files are removed first
		// to put it back on the "create" path.
		if err := os.Remove(certPath); err != nil {
			fmt.Fprintf(os.Stderr, "Error removing existing tenant CA cert: %v\n", err)
			os.Exit(1)
		}
		if err := os.Remove(keyPath); err != nil {
			fmt.Fprintf(os.Stderr, "Error removing existing tenant CA key: %v\n", err)
			os.Exit(1)
		}
	} else if existed {
		fmt.Println("Tenant CA already exists — reporting current state (use --regenerate to replace it):")
	}

	ca, err := handlers_acm.LoadOrCreateTenantCA(certPath, keyPath, domains)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}

	if existed && !regenerate {
		fmt.Println("✅ No changes made.")
	} else {
		fmt.Println("✅ Tenant CA ready.")
	}
	fmt.Printf("   Certificate:      %s\n", certPath)
	fmt.Printf("   Key:              %s (0600)\n", keyPath)
	fmt.Printf("   Permitted domains: %s\n", strings.Join(ca.PermittedDomains(), ", "))
	fmt.Println()
	fmt.Println("Install the certificate into every client's trust store so PRIVATE_CA")
	fmt.Println("certificates are trusted. The tenant CA is only loaded at daemon startup, so")
	fmt.Println("restart spinifex-daemon on any node that started before this CA existed:")
	fmt.Println("  sudo systemctl restart spinifex-daemon")
}
