package handlers_elbv2

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"text/template"

	"github.com/mulgadc/spinifex/spinifex/lbagent"
)

// All interpolated fields are regex-validated at the input boundary.
// HealthCheckPath and HealthCheckMatcher are validated in CreateTargetGroup;
// all other interpolated identifiers go through sanitizeName or are integers.
const haproxyConfigTemplate = `# Auto-generated by spinifex ELBv2 — do not edit
global
    log stdout format short daemon
    stats socket {{.SocketPath}} mode 660 level admin

defaults
    mode http
    log global
    option httplog
    timeout connect 5s
    timeout client 60s
    timeout server 60s
{{range .Frontends}}
frontend {{.Name}}
    bind *:{{.Port}}{{if .CertPath}} ssl crt {{.CertPath}}{{end}}
{{- range .Rules}}
{{- range .ACLs}}
    acl {{.Name}} {{.Expr}}
{{- end}}
    use_backend {{.Backend}} if{{range .ConditionNames}} {{.}}{{end}}
{{- end}}
    default_backend {{.DefaultBackend}}
{{end}}
{{range .Backends}}
backend {{.Name}}
{{- if .Redirect}}
    http-request redirect {{if .Redirect.Scheme}}scheme {{.Redirect.Scheme}}{{else}}location {{.Redirect.Location}}{{end}} code {{.Redirect.Code}}
{{- else if .FixedResponse}}
    http-request return status {{.FixedResponse.StatusCode}}{{if .FixedResponse.ContentType}} content-type "{{.FixedResponse.ContentType}}"{{end}}{{if .FixedResponse.Body}} string "{{.FixedResponse.Body}}"{{end}}
{{- else}}
    balance roundrobin{{if .HealthCheckPath}}
    option httpchk GET {{.HealthCheckPath}}
    http-check expect status {{.HealthCheckMatcher}}{{end}}
{{- range .Servers}}
    server {{.Name}} {{.Addr}}:{{.Port}} check{{if .Secure}} check-ssl ssl verify none{{end}} inter {{.CheckInterval}}s fall {{.Fall}} rise {{.Rise}}
{{- end}}
{{- end}}
{{end}}
`

var haproxyHTTPTmpl = template.Must(template.New("haproxy").Parse(haproxyConfigTemplate))

// HAProxyConfig holds the full configuration for rendering the HAProxy template.
type HAProxyConfig struct {
	SocketPath string
	Frontends  []HAProxyFrontend
	Backends   []HAProxyBackend
	// CertFiles maps each absolute `ssl crt` path referenced by a secure
	// frontend to its combined PEM (cert+chain+key). Not rendered into the
	// template — carried out to the caller for delivery to the LB agent.
	CertFiles map[string]string
}

// HAProxyFrontend represents a listener frontend.
type HAProxyFrontend struct {
	Name           string
	BindAddr       string
	Port           int64
	Protocol       string // listener protocol (HTTP/HTTPS/TCP/TLS); drives TLS termination
	CertPath       string // combined-PEM path for `ssl crt`; empty for non-secure frontends
	DefaultBackend string
	Rules          []HAProxyRule
}

// HAProxyRule represents one routing rule as ACL declarations + a use_backend
// directive. Same-name ACLs are OR'd; distinct ConditionNames are AND'd.
type HAProxyRule struct {
	Backend        string
	ACLs           []HAProxyACL
	ConditionNames []string
}

// HAProxyACL is one acl line. Repeated names express OR over multiple match expressions.
type HAProxyACL struct {
	Name string
	Expr string
}

// HAProxyBackend represents a target group backend, or a synthetic redirect /
// fixed-response backend (server fields unused when those are set).
type HAProxyBackend struct {
	Name               string
	HealthCheckPath    string
	HealthCheckMatcher string
	Servers            []HAProxyServer
	FixedResponse      *HAProxyFixedResponse
	Redirect           *HAProxyRedirect
}

// HAProxyFixedResponse renders an `http-request return` directive. All fields are validated before use.
type HAProxyFixedResponse struct {
	StatusCode  string
	ContentType string
	Body        string
}

// HAProxyRedirect renders an `http-request redirect` directive. Exactly one of
// Scheme (scheme-only, e.g. HTTP→HTTPS) or Location (full rebuilt URL) is set.
type HAProxyRedirect struct {
	Scheme   string
	Location string
	Code     string
}

// HAProxyServer represents a single target server.
type HAProxyServer struct {
	Name          string
	Addr          string
	Port          int64
	CheckInterval int64
	Fall          int64
	Rise          int64
	// Secure re-encrypts traffic and health checks to an HTTPS target group
	// (backend-protocol HTTPS). Without it haproxy speaks plaintext to a TLS
	// backend, its check fails, and the server is marked DOWN (503).
	Secure bool
}

// GenerateHAProxyConfig builds an HAProxy config from the LB, listeners, and
// target groups. No TLS — use GenerateHAProxyConfigWithCerts for HTTPS listeners.
func GenerateHAProxyConfig(lb *LoadBalancerRecord, listeners []*ListenerRecord, tgByArn map[string]*TargetGroupRecord, rulesByListener map[string][]*RuleRecord, bindAddr string) (string, error) {
	config, _, err := GenerateHAProxyConfigWithCerts(lb, listeners, tgByArn, rulesByListener, bindAddr, nil)
	return config, err
}

// GenerateHAProxyConfigWithCerts is GenerateHAProxyConfig plus TLS termination.
// certPEMByArn maps certificate ARNs to combined PEMs; secure frontends emit
// `ssl crt <path>` and the returned certFiles carries path→PEM for the LB agent.
func GenerateHAProxyConfigWithCerts(lb *LoadBalancerRecord, listeners []*ListenerRecord, tgByArn map[string]*TargetGroupRecord, rulesByListener map[string][]*RuleRecord, bindAddr string, certPEMByArn map[string]string) (string, map[string]string, error) {
	// NLBs (L4) render an nginx `stream` config — HAProxy load-balances no UDP.
	if lb.Type == LoadBalancerTypeNetwork {
		return generateNLBStreamConfig(lb, listeners, tgByArn, bindAddr, certPEMByArn)
	}
	return generateALBConfig(lb, listeners, tgByArn, rulesByListener, bindAddr, certPEMByArn)
}

// generateALBConfig builds an HTTP-mode HAProxy config for ALBs.
func generateALBConfig(lb *LoadBalancerRecord, listeners []*ListenerRecord, tgByArn map[string]*TargetGroupRecord, rulesByListener map[string][]*RuleRecord, bindAddr string, certPEMByArn map[string]string) (string, map[string]string, error) {
	cfg, err := buildHAProxyConfig(lb, listeners, tgByArn, rulesByListener, bindAddr, certPEMByArn)
	if err != nil {
		return "", nil, err
	}

	var buf strings.Builder
	if err := haproxyHTTPTmpl.Execute(&buf, cfg); err != nil {
		return "", nil, fmt.Errorf("execute haproxy template: %w", err)
	}

	return buf.String(), cfg.CertFiles, nil
}

// buildHAProxyConfig constructs the HAProxyConfig struct for an ALB (L7).
// NLBs use the nginx data plane (generateNLBStreamConfig), not this builder.
func buildHAProxyConfig(lb *LoadBalancerRecord, listeners []*ListenerRecord, tgByArn map[string]*TargetGroupRecord, rulesByListener map[string][]*RuleRecord, bindAddr string, certPEMByArn map[string]string) (HAProxyConfig, error) {
	socketDir := filepath.Join(os.TempDir(), "spinifex-haproxy")
	// LoadBalancerID already carries the "lb-" prefix; must match the agent's socket path.
	socketPath := filepath.Join(socketDir, fmt.Sprintf("%s.sock", lb.LoadBalancerID))

	cfg := HAProxyConfig{
		SocketPath: socketPath,
	}
	backendAdded := make(map[string]struct{})

	addBackend := func(tgArn string) {
		backendName := sanitizeName("bk", tgArn)
		if _, ok := backendAdded[backendName]; ok {
			return
		}
		tg, ok := tgByArn[tgArn]
		if !ok {
			return
		}

		backend := HAProxyBackend{
			Name:               backendName,
			HealthCheckPath:    tg.HealthCheck.Path,
			HealthCheckMatcher: tg.HealthCheck.Matcher,
		}

		for _, target := range tg.Targets {
			if target.PrivateIP == "" || target.HealthState == TargetHealthDraining {
				continue
			}
			backend.Servers = append(backend.Servers, HAProxyServer{
				Name:          sanitizeName("srv", target.Id),
				Addr:          target.PrivateIP,
				Port:          target.Port,
				CheckInterval: tg.HealthCheck.IntervalSeconds,
				Fall:          tg.HealthCheck.UnhealthyThreshold,
				Rise:          tg.HealthCheck.HealthyThreshold,
				Secure:        strings.EqualFold(tg.Protocol, ProtocolHTTPS),
			})
		}
		cfg.Backends = append(cfg.Backends, backend)
		backendAdded[backendName] = struct{}{}
	}

	addFixedResponseBackend := func(name string, fr *FixedResponseAction) {
		if _, ok := backendAdded[name]; ok {
			return
		}
		hf := &HAProxyFixedResponse{StatusCode: "503"}
		if fr != nil {
			if validHTTPStatusCode(fr.StatusCode) {
				hf.StatusCode = fr.StatusCode
			}
			if validContentType(fr.ContentType) {
				hf.ContentType = fr.ContentType
			}
			if validFixedResponseBody(fr.MessageBody) {
				hf.Body = fr.MessageBody
			}
		}
		cfg.Backends = append(cfg.Backends, HAProxyBackend{Name: name, FixedResponse: hf})
		backendAdded[name] = struct{}{}
	}

	addRedirectBackend := func(name string, rd *HAProxyRedirect) {
		if _, ok := backendAdded[name]; ok {
			return
		}
		cfg.Backends = append(cfg.Backends, HAProxyBackend{Name: name, Redirect: rd})
		backendAdded[name] = struct{}{}
	}

	for _, l := range listeners {
		if len(l.DefaultActions) == 0 {
			continue
		}

		da := l.DefaultActions[0]
		isForwardDefault := da.Type == ActionTypeForward && da.TargetGroupArn != ""

		var defaultBackendName string
		if isForwardDefault {
			defaultBackendName = sanitizeName("bk", da.TargetGroupArn)
		} else {
			// Non-forward default: synthesize a backend for HAProxy's default_backend.
			defaultBackendName = sanitizeName("bkdefault", l.ListenerArn)
		}

		frontend := HAProxyFrontend{
			Name:           sanitizeName("ft", l.ListenerArn),
			BindAddr:       bindAddr,
			Port:           l.Port,
			Protocol:       l.Protocol,
			DefaultBackend: defaultBackendName,
		}

		// Resolve the default cert and stage it for delivery to the agent.
		if protocolRequiresCert(l.Protocol) {
			if pem, path := resolveFrontendCert(lb, l, certPEMByArn); pem != "" {
				frontend.CertPath = path
				if cfg.CertFiles == nil {
					cfg.CertFiles = make(map[string]string)
				}
				cfg.CertFiles[path] = pem
			}
		}

		for _, r := range rulesByListener[l.ListenerArn] {
			backendName, err := registerRuleBackend(r, l, addBackend, addFixedResponseBackend, addRedirectBackend)
			if err != nil {
				return HAProxyConfig{}, err
			}
			rule, err := buildHAProxyRule(r, backendName)
			if err != nil {
				return HAProxyConfig{}, err
			}
			frontend.Rules = append(frontend.Rules, rule)
		}

		cfg.Frontends = append(cfg.Frontends, frontend)
		switch {
		case isForwardDefault:
			addBackend(da.TargetGroupArn)
		case da.Type == ActionTypeRedirect:
			rd, err := buildRedirect(da.Redirect, l)
			if err != nil {
				return HAProxyConfig{}, err
			}
			addRedirectBackend(defaultBackendName, rd)
		default:
			addFixedResponseBackend(defaultBackendName, da.FixedResponse)
		}
	}

	return cfg, nil
}

// frontendCertPath returns the stable absolute PEM path under the agent's cert dir.
func frontendCertPath(lb *LoadBalancerRecord, l *ListenerRecord) string {
	return filepath.Join(lbagent.CertDir, fmt.Sprintf("%s-%s.pem", lb.LoadBalancerID, l.ListenerID))
}

// resolveFrontendCert returns (pem, path) for the listener's default certificate,
// or ("", "") when absent or unresolved.
func resolveFrontendCert(lb *LoadBalancerRecord, l *ListenerRecord, certPEMByArn map[string]string) (pem, path string) {
	if len(l.Certificates) == 0 || certPEMByArn == nil {
		return "", ""
	}
	arn := l.Certificates[0].CertificateArn
	for _, c := range l.Certificates {
		if c.IsDefault {
			arn = c.CertificateArn
			break
		}
	}
	pem, ok := certPEMByArn[arn]
	if !ok || pem == "" {
		return "", ""
	}
	return pem, frontendCertPath(lb, l)
}

// registerRuleBackend registers the backend for a rule's single action and returns its name.
func registerRuleBackend(
	r *RuleRecord,
	l *ListenerRecord,
	addBackend func(string),
	addFixedResponseBackend func(string, *FixedResponseAction),
	addRedirectBackend func(string, *HAProxyRedirect),
) (string, error) {
	if len(r.Actions) == 0 {
		return "", fmt.Errorf("rule %s has no action", r.RuleID)
	}
	a := r.Actions[0]
	switch a.Type {
	case ActionTypeForward:
		if a.TargetGroupArn == "" {
			return "", fmt.Errorf("rule %s forward action has no target group", r.RuleID)
		}
		addBackend(a.TargetGroupArn)
		return sanitizeName("bk", a.TargetGroupArn), nil
	case ActionTypeFixedResponse:
		name := sanitizeName("bkrule", r.RuleID)
		addFixedResponseBackend(name, a.FixedResponse)
		return name, nil
	case ActionTypeRedirect:
		rd, err := buildRedirect(a.Redirect, l)
		if err != nil {
			return "", err
		}
		name := sanitizeName("bkrule", r.RuleID)
		addRedirectBackend(name, rd)
		return name, nil
	default:
		return "", fmt.Errorf("rule %s has unsupported action %q", r.RuleID, a.Type)
	}
}

// buildHAProxyRule converts a RuleRecord's conditions into ACL+use_backend shape.
// Returns an error if any condition value fails render-safe validation.
func buildHAProxyRule(r *RuleRecord, backendName string) (HAProxyRule, error) {
	rule := HAProxyRule{Backend: backendName}

	for ci, c := range r.Conditions {
		aclName := fmt.Sprintf("r%s_c%d", sanitizeACLToken(r.RuleID), ci)
		exprs, err := buildHAProxyACLExprs(c)
		if err != nil {
			return HAProxyRule{}, fmt.Errorf("rule %s condition %d: %w", r.RuleID, ci, err)
		}
		for _, e := range exprs {
			rule.ACLs = append(rule.ACLs, HAProxyACL{Name: aclName, Expr: e})
		}
		rule.ConditionNames = append(rule.ConditionNames, aclName)
	}

	return rule, nil
}

// buildHAProxyACLExprs returns HAProxy ACL expressions for a rule condition.
// Multiple expressions represent OR semantics over the condition's values.
func buildHAProxyACLExprs(c RuleCondition) ([]string, error) {
	switch c.Field {
	case RuleFieldHostHeader:
		return hostOrPathExprs("hdr(host) -i", c.Values)
	case RuleFieldPathPattern:
		return hostOrPathExprs("path", c.Values)
	case RuleFieldHTTPHeader:
		if err := validateRenderSafe(c.HTTPHeaderName); err != nil {
			return nil, err
		}
		out := make([]string, 0, len(c.Values))
		for _, v := range c.Values {
			if err := validateRenderSafe(v); err != nil {
				return nil, err
			}
			out = append(out, fmt.Sprintf("hdr(%s) -i -m str %s", c.HTTPHeaderName, v))
		}
		return out, nil
	case RuleFieldHTTPRequestMethod:
		out := make([]string, 0, len(c.Values))
		for _, v := range c.Values {
			if err := validateRenderSafe(v); err != nil {
				return nil, err
			}
			out = append(out, fmt.Sprintf("method %s", v))
		}
		return out, nil
	case RuleFieldQueryString:
		out := make([]string, 0, len(c.QueryStringKVs))
		for _, kv := range c.QueryStringKVs {
			if err := validateRenderSafe(kv.Value); err != nil {
				return nil, err
			}
			if kv.Key == "" {
				out = append(out, fmt.Sprintf("url_sub %s", kv.Value))
				continue
			}
			if err := validateRenderSafe(kv.Key); err != nil {
				return nil, err
			}
			out = append(out, fmt.Sprintf("urlp(%s) -m str %s", kv.Key, kv.Value))
		}
		return out, nil
	case RuleFieldSourceIP:
		out := make([]string, 0, len(c.Values))
		for _, v := range c.Values {
			if err := validateRenderSafe(v); err != nil {
				return nil, err
			}
			out = append(out, fmt.Sprintf("src %s", v))
		}
		return out, nil
	default:
		return nil, fmt.Errorf("unsupported rule field %q", c.Field)
	}
}

func hostOrPathExprs(prefix string, values []string) ([]string, error) {
	out := make([]string, 0, len(values))
	for _, v := range values {
		if err := validateRenderSafe(v); err != nil {
			return nil, err
		}
		flag, lit := wildcardMatch(v)
		out = append(out, fmt.Sprintf("%s -m %s %s", prefix, flag, lit))
	}
	return out, nil
}

// wildcardMatch maps a host/path pattern to a HAProxy match flag + literal.
// `?` and interior `*` widen to substring — false positives over false negatives.
func wildcardMatch(v string) (flag, literal string) {
	hasLead := strings.HasPrefix(v, "*")
	hasTrail := strings.HasSuffix(v, "*")
	switch {
	case hasLead && hasTrail && len(v) > 2:
		return "sub", v[1 : len(v)-1]
	case hasLead && len(v) > 1:
		return "end", v[1:]
	case hasTrail && len(v) > 1:
		return "beg", v[:len(v)-1]
	case strings.ContainsAny(v, "*?"):
		return "sub", strings.Trim(v, "*?")
	default:
		return "str", v
	}
}

// contentTypeRegex matches a conservative type/subtype MIME string.
var contentTypeRegex = regexp.MustCompile(`^[a-zA-Z0-9!#$&^_.+-]+/[a-zA-Z0-9!#$&^_.+-]+$`)

// validHTTPStatusCode accepts a 3-digit 2xx–5xx HTTP status.
func validHTTPStatusCode(s string) bool {
	if len(s) != 3 || s[0] < '2' || s[0] > '5' {
		return false
	}
	for _, r := range s {
		if r < '0' || r > '9' {
			return false
		}
	}
	return true
}

// validContentType accepts a conservative type/subtype MIME string.
func validContentType(s string) bool {
	return contentTypeRegex.MatchString(s)
}

// validFixedResponseBody rejects bytes that would terminate or inject into the HAProxy directive.
func validFixedResponseBody(s string) bool {
	if s == "" {
		return false
	}
	for _, r := range s {
		if r == '\n' || r == '\r' || r == '"' || r == '\\' || r == '#' {
			return false
		}
	}
	return true
}

// buildRedirect translates a RedirectAction into an HAProxy redirect directive.
// Scheme-only redirects (e.g. HTTP→HTTPS, all other fields default) render as
// `redirect scheme`; everything else rebuilds a `location`.
func buildRedirect(rd *RedirectAction, l *ListenerRecord) (*HAProxyRedirect, error) {
	if rd == nil {
		return nil, fmt.Errorf("redirect action missing config")
	}

	var code string
	switch rd.StatusCode {
	case "HTTP_301":
		code = "301"
	case "HTTP_302":
		code = "302"
	default:
		return nil, fmt.Errorf("redirect has invalid status code %q", rd.StatusCode)
	}

	for _, f := range []string{rd.Protocol, rd.Host, rd.Port, rd.Path, rd.Query} {
		if !validRedirectField(f) {
			return nil, fmt.Errorf("redirect field contains forbidden characters")
		}
	}

	defaultHost := rd.Host == "" || rd.Host == "#{host}"
	defaultPort := rd.Port == "" || rd.Port == "#{port}"
	defaultPath := rd.Path == "" || rd.Path == "#{path}" || rd.Path == "/#{path}"
	defaultQuery := rd.Query == "" || rd.Query == "#{query}"
	explicitScheme := rd.Protocol == ProtocolHTTP || rd.Protocol == ProtocolHTTPS

	if explicitScheme && defaultHost && defaultPort && defaultPath && defaultQuery {
		return &HAProxyRedirect{Scheme: strings.ToLower(rd.Protocol), Code: code}, nil
	}

	scheme := redirectScheme(rd.Protocol, l)
	host := redirectPlaceholders(orDefault(rd.Host, "#{host}"), l)

	port := ""
	if rd.Port != "" && rd.Port != "#{port}" {
		port = ":" + redirectPlaceholders(rd.Port, l)
	}

	path := "%[path]"
	if !defaultPath {
		path = redirectPlaceholders(rd.Path, l)
	}

	query := ""
	if !defaultQuery {
		query = "?" + redirectPlaceholders(rd.Query, l)
	} else if rd.Query == "#{query}" {
		query = "?%[query]"
	}

	return &HAProxyRedirect{Location: scheme + "://" + host + port + path + query, Code: code}, nil
}

func orDefault(s, def string) string {
	if s == "" {
		return def
	}
	return s
}

// redirectScheme resolves the redirect scheme, mapping `#{protocol}` to the listener's protocol.
func redirectScheme(proto string, l *ListenerRecord) string {
	switch proto {
	case ProtocolHTTP, ProtocolHTTPS:
		return strings.ToLower(proto)
	default:
		return strings.ToLower(l.Protocol)
	}
}

// redirectPlaceholders substitutes AWS redirect placeholders with HAProxy log-format fetches.
func redirectPlaceholders(s string, l *ListenerRecord) string {
	r := strings.NewReplacer(
		"#{protocol}", strings.ToLower(l.Protocol),
		"#{host}", "%[req.hdr(host)]",
		"#{port}", strconv.FormatInt(l.Port, 10),
		"#{path}", "%[path]",
		"#{query}", "%[query]",
	)
	return r.Replace(s)
}

// validRedirectField rejects bytes that would break the HAProxy redirect directive.
// Known `#{...}` placeholders are stripped first; any remaining forbidden byte fails.
func validRedirectField(s string) bool {
	known := []string{"#{protocol}", "#{host}", "#{port}", "#{path}", "#{query}"}
	tmp := s
	for _, k := range known {
		tmp = strings.ReplaceAll(tmp, k, "")
	}
	for _, r := range tmp {
		if r < 0x20 || r == 0x7f {
			return false
		}
		switch r {
		case ' ', '"', '#', '%', '[', ']', '\\':
			return false
		}
	}
	return true
}

// validateRenderSafe rejects bytes that could break ACL parsing or inject directives.
// Duplicated from write-time validators so API-bypass cannot leak malicious strings.
func validateRenderSafe(v string) error {
	if v == "" {
		return fmt.Errorf("empty rule token")
	}
	for _, r := range v {
		if r == '\n' || r == '\r' || r == '#' || r == '"' || r == ' ' || r == '\t' {
			return fmt.Errorf("rule token contains forbidden character %q", r)
		}
	}
	return nil
}

// sanitizeACLToken trims an identifier to safe HAProxy ACL-name characters.
func sanitizeACLToken(id string) string {
	var sb strings.Builder
	for _, c := range id {
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') {
			sb.WriteRune(c)
		}
	}
	return sb.String()
}

// sanitizeName creates a safe HAProxy identifier from an ARN or ID.
func sanitizeName(prefix, id string) string {
	// Use last segment of ARN or ID, replace non-alphanumeric with underscore
	parts := strings.Split(id, "/")
	name := parts[len(parts)-1]
	var sb strings.Builder
	for _, c := range name {
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '-' || c == '_' {
			sb.WriteRune(c)
		} else {
			sb.WriteRune('_')
		}
	}
	return prefix + "_" + sb.String()
}
