package handlers_elbv2

import (
	"crypto/x509"
	"encoding/pem"
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"text/template"

	"github.com/mulgadc/spinifex/spinifex/lbagent"
)

// maxDNSNameLen is the longest legal DNS name, so a map key cannot be padded out
// to an unreasonable size by a certificate subject.
const maxDNSNameLen = 253

// NLB (L4) data plane. NLB listeners render an nginx `stream` config because HAProxy
// has no UDP support; ALBs stay on HAProxy. Health checks are passive only
// (max_fails/fail_timeout) — OSS nginx stream has no active upstream probing.

const nginxStreamConfigTemplate = `# Auto-generated by spinifex ELBv2 (NLB) — do not edit
load_module /usr/lib/nginx/modules/ngx_stream_module.so;
user root;
worker_processes auto;
error_log stderr;
pid {{.PIDPath}};

events {
    worker_connections 1024;
}

stream {
{{- range .CertMaps}}
    map $ssl_server_name ${{.Var}} {
        hostnames;
        default {{.DefaultPath}};
{{- range .Entries}}
        "{{.Host}}" {{.Path}};
{{- end}}
    }
{{end}}
{{- range .Upstreams}}
    upstream {{.Name}} {
{{- range .Servers}}
        server {{.Addr}}:{{.Port}} max_fails={{.MaxFails}} fail_timeout={{.FailTimeout}}s;
{{- else}}
        server 127.0.0.1:1 down;
{{- end}}
    }
{{end}}
{{- range .Servers}}
    server {
        listen {{.Port}}{{if .UDP}} udp{{end}}{{if .SSL}} ssl{{end}};
{{- if .SSL}}
        ssl_certificate {{.CertRef}};
        ssl_certificate_key {{.CertRef}};
{{- end}}
{{- if .UDP}}
        proxy_responses 1;
        proxy_timeout 10s;
{{- end}}
        proxy_pass {{.Upstream}};
    }
{{end}}}
`

var nginxStreamTmpl = template.Must(
	template.New("nginx-stream").Parse(nginxStreamConfigTemplate),
)

// nginxConfig is the render model for the NLB nginx `stream` config.
type nginxConfig struct {
	PIDPath   string
	CertMaps  []nginxCertMap
	Upstreams []nginxUpstream
	Servers   []nginxServer
}

// nginxCertMap picks one TLS listener's certificate by SNI name. nginx allows a
// single ssl_certificate per key type in a server block, so several names are
// served by giving the directive a variable and mapping $ssl_server_name to a
// path. `hostnames` in the rendered map is what makes a *.example.com key match
// a subdomain, so a wildcard certificate's SAN works as written.
type nginxCertMap struct {
	Var         string
	DefaultPath string
	Entries     []nginxCertMapEntry
}

// nginxCertMapEntry is one SNI name → PEM path row. Host is lower-cased and
// validated as a hostname before it reaches the config.
type nginxCertMapEntry struct {
	Host string
	Path string
}

// nginxUpstream is one target group's backend pool. An empty pool renders a
// single permanently-down placeholder so nginx (which requires >=1 server)
// still validates.
type nginxUpstream struct {
	Name    string
	Servers []nginxUpstreamServer
}

type nginxUpstreamServer struct {
	Addr        string
	Port        int64
	MaxFails    int64
	FailTimeout int64
}

// nginxServer is one listener's `server` block. TCP_UDP listeners expand to two
// blocks on the same port (one TCP, one UDP).
type nginxServer struct {
	Port int64
	UDP  bool
	SSL  bool
	// CertRef is what ssl_certificate is given: a literal PEM path for a
	// single-certificate listener, or `$var` naming this listener's cert map.
	CertRef  string
	Upstream string
}

// engineForType reports the data-plane engine for a load balancer type: nginx
// for NLBs (L4), HAProxy for everything else (ALB / L7).
func engineForType(lbType string) string {
	if lbType == LoadBalancerTypeNetwork {
		return EngineNginx
	}
	return EngineHAProxy
}

// generateNLBStreamConfig builds an nginx `stream` config for an NLB; TLS listeners
// terminate at nginx. certFiles maps cert path → combined PEM for delivery to the
// agent. bindAddr is unused — nginx listens on all addresses like HAProxy's `bind *`.
func generateNLBStreamConfig(lb *LoadBalancerRecord, listeners []*ListenerRecord, tgByArn map[string]*TargetGroupRecord, _ string, certPEMByArn map[string]string) (string, map[string]string, error) {
	cfg := nginxConfig{PIDPath: lbagent.NginxPIDPath}
	var certFiles map[string]string
	upstreamAdded := make(map[string]struct{})

	addUpstream := func(tgArn string) string {
		name := sanitizeName("us", tgArn)
		if _, ok := upstreamAdded[name]; ok {
			return name
		}
		us := nginxUpstream{Name: name}
		if tg, ok := tgByArn[tgArn]; ok {
			for _, t := range tg.Targets {
				if t.PrivateIP == "" || t.HealthState == TargetHealthDraining {
					continue
				}
				us.Servers = append(us.Servers, nginxUpstreamServer{
					Addr:        t.PrivateIP,
					Port:        t.Port,
					MaxFails:    tg.HealthCheck.UnhealthyThreshold,
					FailTimeout: tg.HealthCheck.IntervalSeconds,
				})
			}
		}
		cfg.Upstreams = append(cfg.Upstreams, us)
		upstreamAdded[name] = struct{}{}
		return name
	}

	for _, l := range listeners {
		if len(l.DefaultActions) == 0 {
			continue
		}
		da := l.DefaultActions[0]
		// NLB default actions are forward-only (no redirect / fixed-response).
		if da.Type != ActionTypeForward || da.TargetGroupArn == "" {
			continue
		}
		upstream := addUpstream(da.TargetGroupArn)

		var certRef string
		if protocolRequiresCert(l.Protocol) {
			ref, certMap, files := buildNginxCerts(lb, l, certPEMByArn)
			certRef = ref
			if certMap != nil {
				cfg.CertMaps = append(cfg.CertMaps, *certMap)
			}
			for path, pem := range files {
				if certFiles == nil {
					certFiles = make(map[string]string)
				}
				certFiles[path] = pem
			}
		}

		switch l.Protocol {
		case ProtocolUDP:
			cfg.Servers = append(cfg.Servers, nginxServer{Port: l.Port, UDP: true, Upstream: upstream})
		case ProtocolTCPUDP:
			cfg.Servers = append(cfg.Servers,
				nginxServer{Port: l.Port, Upstream: upstream},
				nginxServer{Port: l.Port, UDP: true, Upstream: upstream})
		default: // TCP, TLS
			cfg.Servers = append(cfg.Servers, nginxServer{
				Port:     l.Port,
				SSL:      certRef != "",
				CertRef:  certRef,
				Upstream: upstream,
			})
		}
	}

	var buf strings.Builder
	if err := nginxStreamTmpl.Execute(&buf, cfg); err != nil {
		return "", nil, fmt.Errorf("execute nginx stream template: %w", err)
	}
	return buf.String(), certFiles, nil
}

// buildNginxCerts resolves a TLS listener's certificates into the value for
// ssl_certificate, an optional SNI map, and the PEMs to deliver. One certificate
// renders as a literal path: a variable path makes nginx read the PEM on every
// handshake, which the single-certificate case should not pay for.
func buildNginxCerts(lb *LoadBalancerRecord, l *ListenerRecord, certPEMByArn map[string]string) (string, *nginxCertMap, map[string]string) {
	certs := resolveFrontendCerts(lbagent.NginxCertDir, lb, l, certPEMByArn)
	if len(certs) == 0 {
		return "", nil, nil
	}

	files := map[string]string{certs[0].Path: certs[0].PEM}
	if len(certs) == 1 {
		return certs[0].Path, nil, files
	}

	cm := nginxCertMap{Var: nginxCertVar(l), DefaultPath: certs[0].Path}
	claimed := make(map[string]bool)
	for i, c := range certs {
		names := certDNSNames(c.PEM)
		if i == 0 {
			// The default already answers every unmatched name, so it needs no
			// rows — but its own names are claimed so no later certificate can
			// take them. nginx rejects a duplicate map key outright.
			for _, h := range names {
				claimed[h] = true
			}
			continue
		}
		var selectable bool
		for _, h := range names {
			if claimed[h] {
				continue
			}
			claimed[h] = true
			cm.Entries = append(cm.Entries, nginxCertMapEntry{Host: h, Path: c.Path})
			selectable = true
		}
		// A certificate no SNI name can select would only strand its private key
		// on the load balancer, so it is not delivered.
		if selectable {
			files[c.Path] = c.PEM
		}
	}

	if len(cm.Entries) == 0 {
		return cm.DefaultPath, nil, files
	}
	return "$" + cm.Var, &cm, files
}

// nginxCertVar names the per-listener map variable. Scoped to the listener
// because a map lives at stream level, and two listeners may attach different
// certificates for the same name. nginx variables allow only [A-Za-z0-9_], which
// sanitizeName's hyphens would break.
func nginxCertVar(l *ListenerRecord) string {
	return strings.ReplaceAll(sanitizeName("sslcert", l.ListenerID), "-", "_")
}

// nginxDNSNameRegex matches a hostname usable as a map key, optionally wildcarded
// in the leftmost label. Deliberately stricter than the rule-condition host regex:
// these come from a caller-supplied certificate subject and land in the config.
var nginxDNSNameRegex = regexp.MustCompile(`^(\*\.)?[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$`)

// certDNSNames returns the names a combined PEM's leaf can be selected by: its
// DNS SANs, or the subject CN when it has none. Anything that is not plainly a
// hostname is dropped rather than rendered.
func certDNSNames(combinedPEM string) []string {
	leaf := parseLeafCert(combinedPEM)
	if leaf == nil {
		return nil
	}
	names := leaf.DNSNames
	if len(names) == 0 && leaf.Subject.CommonName != "" {
		names = []string{leaf.Subject.CommonName}
	}

	out := make([]string, 0, len(names))
	for _, n := range names {
		n = strings.ToLower(strings.TrimSpace(n))
		if len(n) <= maxDNSNameLen && nginxDNSNameRegex.MatchString(n) {
			out = append(out, n)
		}
	}
	return out
}

// parseLeafCert returns the first certificate in a combined cert+chain+key PEM,
// which is the leaf by convention of how the material is assembled.
func parseLeafCert(combinedPEM string) *x509.Certificate {
	rest := []byte(combinedPEM)
	for {
		block, remainder := pem.Decode(rest)
		if block == nil {
			return nil
		}
		rest = remainder
		if block.Type != "CERTIFICATE" {
			continue
		}
		leaf, err := x509.ParseCertificate(block.Bytes)
		if err != nil {
			return nil
		}
		return leaf
	}
}

// buildNLBHealthTargets returns backends the agent actively probes (nginx stream
// has no built-in active probing). ServerName matches sanitizeName("srv", target.Id);
// sorted by name for deterministic delivery.
func buildNLBHealthTargets(tgByArn map[string]*TargetGroupRecord) []HealthTargetSpec {
	var out []HealthTargetSpec
	for _, tg := range tgByArn {
		for _, t := range tg.Targets {
			if t.PrivateIP == "" || t.HealthState == TargetHealthDraining {
				continue
			}
			out = append(out, HealthTargetSpec{
				ServerName: sanitizeName("srv", t.Id),
				Address:    fmt.Sprintf("%s:%d", t.PrivateIP, nlbHealthCheckPort(tg, t)),
				Protocol:   nlbHealthCheckProtocol(tg),
				Path:       tg.HealthCheck.Path,
			})
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ServerName < out[j].ServerName })
	return out
}

// nlbHealthCheckProtocol returns the target group's health-check protocol,
// defaulting to the NLB default (TCP) when unset.
func nlbHealthCheckProtocol(tg *TargetGroupRecord) string {
	if tg.HealthCheck.Protocol != "" {
		return tg.HealthCheck.Protocol
	}
	return DefaultNLBHealthCheckProtocol
}

// nlbHealthCheckPort resolves the probe port: an explicit numeric health-check
// port wins, otherwise "traffic-port" maps to the target's port (or the target
// group's default port when the target has none).
func nlbHealthCheckPort(tg *TargetGroupRecord, t Target) int64 {
	if p := tg.HealthCheck.Port; p != "" && p != DefaultHealthCheckPort {
		if n, err := strconv.ParseInt(p, 10, 64); err == nil {
			return n
		}
	}
	if t.Port != 0 {
		return t.Port
	}
	return tg.Port
}
