package handlers_elbv2

import (
	"fmt"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"text/template"

	"github.com/mulgadc/spinifex/spinifex/lbagent"
)

// NLB (L4) data plane. NLB listeners render an nginx `stream` config because HAProxy
// has no UDP support; ALBs stay on HAProxy. Health checks are passive only
// (max_fails/fail_timeout) — OSS nginx stream has no active upstream probing.

const nginxStreamConfigTemplate = `# Auto-generated by spinifex ELBv2 (NLB) — do not edit
load_module /usr/lib/nginx/modules/ngx_stream_module.so;
user root;
worker_processes auto;
error_log stderr;
pid {{.PIDPath}};

events {
    worker_connections 1024;
}

stream {
{{- range .Upstreams}}
    upstream {{.Name}} {
{{- range .Servers}}
        server {{.Addr}}:{{.Port}} max_fails={{.MaxFails}} fail_timeout={{.FailTimeout}}s;
{{- else}}
        server 127.0.0.1:1 down;
{{- end}}
    }
{{end}}
{{- range .Servers}}
    server {
        listen {{.Port}}{{if .UDP}} udp{{end}}{{if .SSL}} ssl{{end}};
{{- if .SSL}}
        ssl_certificate {{.CertPath}};
        ssl_certificate_key {{.CertPath}};
{{- end}}
{{- if .UDP}}
        proxy_responses 1;
        proxy_timeout 10s;
{{- end}}
        proxy_pass {{.Upstream}};
    }
{{end}}}
`

var nginxStreamTmpl = template.Must(
	template.New("nginx-stream").Parse(nginxStreamConfigTemplate),
)

// nginxConfig is the render model for the NLB nginx `stream` config.
type nginxConfig struct {
	PIDPath   string
	Upstreams []nginxUpstream
	Servers   []nginxServer
}

// nginxUpstream is one target group's backend pool. An empty pool renders a
// single permanently-down placeholder so nginx (which requires >=1 server)
// still validates.
type nginxUpstream struct {
	Name    string
	Servers []nginxUpstreamServer
}

type nginxUpstreamServer struct {
	Addr        string
	Port        int64
	MaxFails    int64
	FailTimeout int64
}

// nginxServer is one listener's `server` block. TCP_UDP listeners expand to two
// blocks on the same port (one TCP, one UDP).
type nginxServer struct {
	Port     int64
	UDP      bool
	SSL      bool
	CertPath string
	Upstream string
}

// engineForType reports the data-plane engine for a load balancer type: nginx
// for NLBs (L4), HAProxy for everything else (ALB / L7).
func engineForType(lbType string) string {
	if lbType == LoadBalancerTypeNetwork {
		return EngineNginx
	}
	return EngineHAProxy
}

// generateNLBStreamConfig builds an nginx `stream` config for an NLB; TLS listeners
// terminate at nginx. certFiles maps cert path → combined PEM for delivery to the
// agent. bindAddr is unused — nginx listens on all addresses like HAProxy's `bind *`.
func generateNLBStreamConfig(lb *LoadBalancerRecord, listeners []*ListenerRecord, tgByArn map[string]*TargetGroupRecord, _ string, certPEMByArn map[string]string) (string, map[string]string, error) {
	cfg := nginxConfig{PIDPath: lbagent.NginxPIDPath}
	var certFiles map[string]string
	upstreamAdded := make(map[string]struct{})

	addUpstream := func(tgArn string) string {
		name := sanitizeName("us", tgArn)
		if _, ok := upstreamAdded[name]; ok {
			return name
		}
		us := nginxUpstream{Name: name}
		if tg, ok := tgByArn[tgArn]; ok {
			for _, t := range tg.Targets {
				if t.PrivateIP == "" || t.HealthState == TargetHealthDraining {
					continue
				}
				us.Servers = append(us.Servers, nginxUpstreamServer{
					Addr:        t.PrivateIP,
					Port:        t.Port,
					MaxFails:    tg.HealthCheck.UnhealthyThreshold,
					FailTimeout: tg.HealthCheck.IntervalSeconds,
				})
			}
		}
		cfg.Upstreams = append(cfg.Upstreams, us)
		upstreamAdded[name] = struct{}{}
		return name
	}

	for _, l := range listeners {
		if len(l.DefaultActions) == 0 {
			continue
		}
		da := l.DefaultActions[0]
		// NLB default actions are forward-only (no redirect / fixed-response).
		if da.Type != ActionTypeForward || da.TargetGroupArn == "" {
			continue
		}
		upstream := addUpstream(da.TargetGroupArn)

		var certPath string
		if protocolRequiresCert(l.Protocol) {
			pem, _ := resolveFrontendCert(lb, l, certPEMByArn)
			if pem != "" {
				certPath = nginxCertPath(lb, l)
				if certFiles == nil {
					certFiles = make(map[string]string)
				}
				certFiles[certPath] = pem
			}
		}

		switch l.Protocol {
		case ProtocolUDP:
			cfg.Servers = append(cfg.Servers, nginxServer{Port: l.Port, UDP: true, Upstream: upstream})
		case ProtocolTCPUDP:
			cfg.Servers = append(cfg.Servers,
				nginxServer{Port: l.Port, Upstream: upstream},
				nginxServer{Port: l.Port, UDP: true, Upstream: upstream})
		default: // TCP, TLS
			cfg.Servers = append(cfg.Servers, nginxServer{
				Port:     l.Port,
				SSL:      certPath != "",
				CertPath: certPath,
				Upstream: upstream,
			})
		}
	}

	var buf strings.Builder
	if err := nginxStreamTmpl.Execute(&buf, cfg); err != nil {
		return "", nil, fmt.Errorf("execute nginx stream template: %w", err)
	}
	return buf.String(), certFiles, nil
}

// nginxCertPath is the stable absolute PEM path for a TLS listener under the
// agent's nginx cert dir. Daemon-rendered and agent-written paths must match.
func nginxCertPath(lb *LoadBalancerRecord, l *ListenerRecord) string {
	return filepath.Join(lbagent.NginxCertDir, fmt.Sprintf("%s-%s.pem", lb.LoadBalancerID, l.ListenerID))
}

// buildNLBHealthTargets returns backends the agent actively probes (nginx stream
// has no built-in active probing). ServerName matches sanitizeName("srv", target.Id);
// sorted by name for deterministic delivery.
func buildNLBHealthTargets(tgByArn map[string]*TargetGroupRecord) []HealthTargetSpec {
	var out []HealthTargetSpec
	for _, tg := range tgByArn {
		for _, t := range tg.Targets {
			if t.PrivateIP == "" || t.HealthState == TargetHealthDraining {
				continue
			}
			out = append(out, HealthTargetSpec{
				ServerName: sanitizeName("srv", t.Id),
				Address:    fmt.Sprintf("%s:%d", t.PrivateIP, nlbHealthCheckPort(tg, t)),
				Protocol:   nlbHealthCheckProtocol(tg),
				Path:       tg.HealthCheck.Path,
			})
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ServerName < out[j].ServerName })
	return out
}

// nlbHealthCheckProtocol returns the target group's health-check protocol,
// defaulting to the NLB default (TCP) when unset.
func nlbHealthCheckProtocol(tg *TargetGroupRecord) string {
	if tg.HealthCheck.Protocol != "" {
		return tg.HealthCheck.Protocol
	}
	return DefaultNLBHealthCheckProtocol
}

// nlbHealthCheckPort resolves the probe port: an explicit numeric health-check
// port wins, otherwise "traffic-port" maps to the target's port (or the target
// group's default port when the target has none).
func nlbHealthCheckPort(tg *TargetGroupRecord, t Target) int64 {
	if p := tg.HealthCheck.Port; p != "" && p != DefaultHealthCheckPort {
		if n, err := strconv.ParseInt(p, 10, 64); err == nil {
			return n
		}
	}
	if t.Port != 0 {
		return t.Port
	}
	return tg.Port
}
