# Domain configuration file in TOML format.
version = "3"
epoch = 1
node = "{{.Node}}"
{{- if .OperatorEmail}}

[operator]
email = "{{.OperatorEmail}}"
{{- end}}

[aws]
region = "{{.Region}}"
internal_suffix = "spinifex.internal"

[network]
ipsec_enabled = {{.IPSecEnabled}}
{{- if .ExternalMode}}
external_mode = "{{.ExternalMode}}"

[[network.external_pools]]
name        = "{{.PoolName}}"
{{- if .PoolSource}}
source      = "{{.PoolSource}}"
{{- end}}
{{- if .PoolBindBridge}}
bind_bridge = "{{.PoolBindBridge}}"
{{- end}}
{{- if .PoolStart}}
range_start = "{{.PoolStart}}"
range_end   = "{{.PoolEnd}}"
{{- end}}
{{- if .PoolGateway}}
gateway     = "{{.PoolGateway}}"
{{- end}}
{{- if .PoolGatewayIP}}
gateway_ip  = "{{.PoolGatewayIP}}"
{{- end}}
prefix_len  = {{if .PoolPrefixLen}}{{.PoolPrefixLen}}{{else}}24{{end}}
{{- if .PoolDNSServers}}
dns_servers = [{{range $i, $s := .PoolDNSServers}}{{if $i}}, {{end}}"{{$s}}"{{end}}]
{{- end}}
{{- end}}
{{- if .BootstrapVpcId}}

[bootstrap]
account_id  = "{{.BootstrapAccountId}}"
vpc_id      = "{{.BootstrapVpcId}}"
subnet_id   = "{{.BootstrapSubnetId}}"
igw_id      = "{{.BootstrapIgwId}}"
cidr        = "{{.BootstrapCidr}}"
subnet_cidr = "{{.BootstrapSubnetCidr}}"
{{- end}}

[nodes.{{.Node}}]
node = "{{.Node}}"
host = "{{.BindIP}}"
{{- if .AdvertiseIP}}
advertise = "{{.AdvertiseIP}}"
{{- end}}
region = "{{.Region}}"
az = "{{.Az}}"
data_dir = "{{.DataDir}}"
{{- if .Services}}
services = [{{range $i, $s := .Services}}{{if $i}}, {{end}}"{{$s}}"{{end}}]
{{- end}}

account_id = "{{.AccountID}}"

[nodes.{{.Node}}.daemon]
host = "{{.BindIP}}:{{.Port}}"
tlskey = "config/server.key"
tlscert = "config/server.pem"
{{- if .ExternalMode}}
dev_networking = false
{{- else}}
dev_networking = true
{{- end}}
{{- if .GPUPassthrough}}
gpu_passthrough = true
{{- end}}

[nodes.{{.Node}}.awsgw]
host = "{{.BindIP}}:9999"
tlskey = "config/server.key"
tlscert = "config/server.pem"
debug = true
config = "awsgw/awsgw.toml"

[nodes.{{.Node}}.nats]
host = "{{.BindIP}}:4222"
cacert = "{{.ConfigDir}}/ca.pem"

[nodes.{{.Node}}.nats.acl]
token = "{{.NatsToken}}"

[nodes.{{.Node}}.nats.sub]

[nodes.{{.Node}}.viperblock]
shardwal = false
{{- if .EncryptionKeyFile}}
encryption_key_file = "{{.EncryptionKeyFile}}"
{{- end}}

[nodes.{{.Node}}.vpcd]
ovn_nb_addr = "{{.OVNNBAddr}}"
ovn_sb_addr = "{{.OVNSBAddr}}"
{{- if .ExternalIface}}
external_interface = "{{.ExternalIface}}"
{{- end}}

[nodes.{{.Node}}.predastore]
host = "{{.BindIP}}:8443"
region = "{{.Region}}"
bucket = "predastore"
accesskey = "{{.AccessKey}}"
secretkey = "{{.SecretKey}}"
{{- if gt .PredastoreNodeID 0}}
node_id = {{.PredastoreNodeID}}
{{- end}}
{{- range .RemoteNodes}}

[nodes.{{.Name}}]
node = "{{.Name}}"
host = "{{.Host}}"
region = "{{.Region}}"
az = "{{.AZ}}"
{{- if .Services}}
services = [{{range $i, $s := .Services}}{{if $i}}, {{end}}"{{$s}}"{{end}}]
{{- end}}
{{- end}}
