//go:build ignore

// Command generate regenerates units_gen.go from build/systemd, the single
// source of truth for spinifex unit files. go:embed cannot reach outside
// this package directory, so the contents are baked in as a Go map instead.
package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "generate:", err)
		os.Exit(1)
	}
}

func run() error {
	selfDir, err := os.Getwd()
	if err != nil {
		return err
	}
	unitsDir := filepath.Join(selfDir, "..", "..", "build", "systemd")

	ents, err := os.ReadDir(unitsDir)
	if err != nil {
		return fmt.Errorf("read %s: %w", unitsDir, err)
	}

	var names []string
	for _, e := range ents {
		n := e.Name()
		for _, suffix := range []string{".service", ".slice", ".target", ".timer"} {
			if strings.HasSuffix(n, suffix) {
				names = append(names, n)
				break
			}
		}
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("// Code generated by `go generate ./...` from build/systemd; DO NOT EDIT.\n\n")
	b.WriteString("package systemd\n\n")
	b.WriteString("// Units maps each core unit file name to its embedded contents, sourced from\n")
	b.WriteString("// build/systemd at generation time. Regenerate with `go generate ./...` after\n")
	b.WriteString("// editing a unit; units_invariants_test.go fails preflight if this drifts.\n")
	b.WriteString("var Units = map[string]string{\n")
	for _, name := range names {
		content, err := os.ReadFile(filepath.Join(unitsDir, name))
		if err != nil {
			return fmt.Errorf("read %s: %w", name, err)
		}
		fmt.Fprintf(&b, "\t%q: %q,\n", name, string(content))
	}
	b.WriteString("}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return fmt.Errorf("format generated source: %w", err)
	}

	outPath := filepath.Join(selfDir, "units_gen.go")
	return os.WriteFile(outPath, formatted, 0o644)
}
