/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthNodesRouteImport } from './routes/_auth/nodes'
import { Route as AuthS3ServiceMetricsRouteImport } from './routes/_auth/s3/service-metrics'
import { Route as AuthS3LsIndexRouteImport } from './routes/_auth/s3/ls/index'
import { Route as AuthS3bucketsCreateBucketRouteImport } from './routes/_auth/s3/(buckets)/create-bucket'
import { Route as AuthIamusersCreateUserRouteImport } from './routes/_auth/iam/(users)/create-user'
import { Route as AuthIamrolesCreateRoleRouteImport } from './routes/_auth/iam/(roles)/create-role'
import { Route as AuthIampoliciesCreatePolicyRouteImport } from './routes/_auth/iam/(policies)/create-policy'
import { Route as AuthIaminstanceProfilesCreateInstanceProfileRouteImport } from './routes/_auth/iam/(instance-profiles)/create-instance-profile'
import { Route as AuthEksclustersCreateClusterRouteImport } from './routes/_auth/eks/(clusters)/create-cluster'
import { Route as AuthEcsclustersTaskDefinitionsRouteImport } from './routes/_auth/ecs/(clusters)/task-definitions'
import { Route as AuthEcsclustersRunTaskRouteImport } from './routes/_auth/ecs/(clusters)/run-task'
import { Route as AuthEcsclustersRegisterTaskDefinitionRouteImport } from './routes/_auth/ecs/(clusters)/register-task-definition'
import { Route as AuthEcsclustersCreateServiceRouteImport } from './routes/_auth/ecs/(clusters)/create-service'
import { Route as AuthEc2vpcCreateVpcRouteImport } from './routes/_auth/ec2/(vpc)/create-vpc'
import { Route as AuthEc2volumesCreateVolumeRouteImport } from './routes/_auth/ec2/(volumes)/create-volume'
import { Route as AuthEc2targetGroupsCreateTargetGroupRouteImport } from './routes/_auth/ec2/(target-groups)/create-target-group'
import { Route as AuthEc2subnetCreateSubnetRouteImport } from './routes/_auth/ec2/(subnet)/create-subnet'
import { Route as AuthEc2snapshotsCreateSnapshotRouteImport } from './routes/_auth/ec2/(snapshots)/create-snapshot'
import { Route as AuthEc2securityGroupsCreateSecurityGroupRouteImport } from './routes/_auth/ec2/(security-groups)/create-security-group'
import { Route as AuthEc2routeTablesCreateRouteTableRouteImport } from './routes/_auth/ec2/(route-tables)/create-route-table'
import { Route as AuthEc2placementGroupsCreatePlacementGroupRouteImport } from './routes/_auth/ec2/(placement-groups)/create-placement-group'
import { Route as AuthEc2natGatewaysCreateNatGatewayRouteImport } from './routes/_auth/ec2/(nat-gateways)/create-nat-gateway'
import { Route as AuthEc2loadBalancersCreateLoadBalancerRouteImport } from './routes/_auth/ec2/(load-balancers)/create-load-balancer'
import { Route as AuthEc2keyImportKeyPairRouteImport } from './routes/_auth/ec2/(key)/import-key-pair'
import { Route as AuthEc2keyCreateKeyPairRouteImport } from './routes/_auth/ec2/(key)/create-key-pair'
import { Route as AuthEc2internetGatewaysCreateInternetGatewayRouteImport } from './routes/_auth/ec2/(internet-gateways)/create-internet-gateway'
import { Route as AuthEc2instancesRunInstancesRouteImport } from './routes/_auth/ec2/(instances)/run-instances'
import { Route as AuthEc2elasticIpsAllocateAddressRouteImport } from './routes/_auth/ec2/(elastic-ips)/allocate-address'
import { Route as AuthS3LsBucketRouteRouteImport } from './routes/_auth/s3/ls/$bucket/route'
import { Route as AuthS3LsBucketIndexRouteImport } from './routes/_auth/s3/ls/$bucket/index'
import { Route as AuthIamusersListUsersIndexRouteImport } from './routes/_auth/iam/(users)/list-users/index'
import { Route as AuthIamrolesListRolesIndexRouteImport } from './routes/_auth/iam/(roles)/list-roles/index'
import { Route as AuthIampoliciesListPoliciesIndexRouteImport } from './routes/_auth/iam/(policies)/list-policies/index'
import { Route as AuthIaminstanceProfilesListInstanceProfilesIndexRouteImport } from './routes/_auth/iam/(instance-profiles)/list-instance-profiles/index'
import { Route as AuthEksclustersListClustersIndexRouteImport } from './routes/_auth/eks/(clusters)/list-clusters/index'
import { Route as AuthEcsclustersListClustersIndexRouteImport } from './routes/_auth/ecs/(clusters)/list-clusters/index'
import { Route as AuthEcrrepositoriesListRepositoriesIndexRouteImport } from './routes/_auth/ecr/(repositories)/list-repositories/index'
import { Route as AuthEc2vpcDescribeVpcsIndexRouteImport } from './routes/_auth/ec2/(vpc)/describe-vpcs/index'
import { Route as AuthEc2volumesDescribeVolumesIndexRouteImport } from './routes/_auth/ec2/(volumes)/describe-volumes/index'
import { Route as AuthEc2targetGroupsDescribeTargetGroupsIndexRouteImport } from './routes/_auth/ec2/(target-groups)/describe-target-groups/index'
import { Route as AuthEc2subnetDescribeSubnetsIndexRouteImport } from './routes/_auth/ec2/(subnet)/describe-subnets/index'
import { Route as AuthEc2snapshotsDescribeSnapshotsIndexRouteImport } from './routes/_auth/ec2/(snapshots)/describe-snapshots/index'
import { Route as AuthEc2securityGroupsDescribeSecurityGroupsIndexRouteImport } from './routes/_auth/ec2/(security-groups)/describe-security-groups/index'
import { Route as AuthEc2routeTablesDescribeRouteTablesIndexRouteImport } from './routes/_auth/ec2/(route-tables)/describe-route-tables/index'
import { Route as AuthEc2placementGroupsDescribePlacementGroupsIndexRouteImport } from './routes/_auth/ec2/(placement-groups)/describe-placement-groups/index'
import { Route as AuthEc2natGatewaysDescribeNatGatewaysIndexRouteImport } from './routes/_auth/ec2/(nat-gateways)/describe-nat-gateways/index'
import { Route as AuthEc2loadBalancersDescribeLoadBalancersIndexRouteImport } from './routes/_auth/ec2/(load-balancers)/describe-load-balancers/index'
import { Route as AuthEc2keyDescribeKeyPairsIndexRouteImport } from './routes/_auth/ec2/(key)/describe-key-pairs/index'
import { Route as AuthEc2internetGatewaysDescribeInternetGatewaysIndexRouteImport } from './routes/_auth/ec2/(internet-gateways)/describe-internet-gateways/index'
import { Route as AuthEc2instancesDescribeInstancesIndexRouteImport } from './routes/_auth/ec2/(instances)/describe-instances/index'
import { Route as AuthEc2imagesDescribeImagesIndexRouteImport } from './routes/_auth/ec2/(images)/describe-images/index'
import { Route as AuthEc2elasticIpsDescribeAddressesIndexRouteImport } from './routes/_auth/ec2/(elastic-ips)/describe-addresses/index'
import { Route as AuthS3LsBucketSplatRouteImport } from './routes/_auth/s3/ls/$bucket/$'
import { Route as AuthIamusersListUsersUserNameRouteImport } from './routes/_auth/iam/(users)/list-users/$userName'
import { Route as AuthIamrolesListRolesRoleNameRouteImport } from './routes/_auth/iam/(roles)/list-roles/$roleName'
import { Route as AuthIampoliciesListPoliciesPolicyArnRouteImport } from './routes/_auth/iam/(policies)/list-policies/$policyArn'
import { Route as AuthIaminstanceProfilesListInstanceProfilesInstanceProfileNameRouteImport } from './routes/_auth/iam/(instance-profiles)/list-instance-profiles/$instanceProfileName'
import { Route as AuthEksclustersListClustersClusterNameRouteImport } from './routes/_auth/eks/(clusters)/list-clusters/$clusterName'
import { Route as AuthEcsclustersListClustersClusterNameRouteImport } from './routes/_auth/ecs/(clusters)/list-clusters/$clusterName'
import { Route as AuthEcrrepositoriesListRepositoriesIdRouteImport } from './routes/_auth/ecr/(repositories)/list-repositories/$id'
import { Route as AuthEc2vpcDescribeVpcsIdRouteImport } from './routes/_auth/ec2/(vpc)/describe-vpcs/$id'
import { Route as AuthEc2volumesModifyVolumeIdRouteImport } from './routes/_auth/ec2/(volumes)/modify-volume/$id'
import { Route as AuthEc2volumesDescribeVolumesIdRouteImport } from './routes/_auth/ec2/(volumes)/describe-volumes/$id'
import { Route as AuthEc2targetGroupsDescribeTargetGroupsIdRouteImport } from './routes/_auth/ec2/(target-groups)/describe-target-groups/$id'
import { Route as AuthEc2subnetDescribeSubnetsIdRouteImport } from './routes/_auth/ec2/(subnet)/describe-subnets/$id'
import { Route as AuthEc2snapshotsDescribeSnapshotsIdRouteImport } from './routes/_auth/ec2/(snapshots)/describe-snapshots/$id'
import { Route as AuthEc2securityGroupsDescribeSecurityGroupsIdRouteImport } from './routes/_auth/ec2/(security-groups)/describe-security-groups/$id'
import { Route as AuthEc2routeTablesDescribeRouteTablesIdRouteImport } from './routes/_auth/ec2/(route-tables)/describe-route-tables/$id'
import { Route as AuthEc2placementGroupsDescribePlacementGroupsIdRouteImport } from './routes/_auth/ec2/(placement-groups)/describe-placement-groups/$id'
import { Route as AuthEc2natGatewaysDescribeNatGatewaysIdRouteImport } from './routes/_auth/ec2/(nat-gateways)/describe-nat-gateways/$id'
import { Route as AuthEc2loadBalancersDescribeLoadBalancersIdRouteImport } from './routes/_auth/ec2/(load-balancers)/describe-load-balancers/$id'
import { Route as AuthEc2keyDescribeKeyPairsIdRouteImport } from './routes/_auth/ec2/(key)/describe-key-pairs/$id'
import { Route as AuthEc2internetGatewaysDescribeInternetGatewaysIdRouteImport } from './routes/_auth/ec2/(internet-gateways)/describe-internet-gateways/$id'
import { Route as AuthEc2instancesDescribeInstancesIdRouteImport } from './routes/_auth/ec2/(instances)/describe-instances/$id'
import { Route as AuthEc2imagesDescribeImagesIdRouteImport } from './routes/_auth/ec2/(images)/describe-images/$id'
import { Route as AuthEc2elasticIpsDescribeAddressesIdRouteImport } from './routes/_auth/ec2/(elastic-ips)/describe-addresses/$id'
import { Route as AuthEcsclustersListClustersClusterNameTasksTaskIdRouteImport } from './routes/_auth/ecs/(clusters)/list-clusters/$clusterName_/tasks/$taskId'
import { Route as AuthEcsclustersListClustersClusterNameServicesServiceNameRouteImport } from './routes/_auth/ecs/(clusters)/list-clusters/$clusterName_/services/$serviceName'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthNodesRoute = AuthNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthS3ServiceMetricsRoute = AuthS3ServiceMetricsRouteImport.update({
  id: '/s3/service-metrics',
  path: '/s3/service-metrics',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthS3LsIndexRoute = AuthS3LsIndexRouteImport.update({
  id: '/s3/ls/',
  path: '/s3/ls/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthS3bucketsCreateBucketRoute =
  AuthS3bucketsCreateBucketRouteImport.update({
    id: '/s3/(buckets)/create-bucket',
    path: '/s3/create-bucket',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthIamusersCreateUserRoute = AuthIamusersCreateUserRouteImport.update({
  id: '/iam/(users)/create-user',
  path: '/iam/create-user',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthIamrolesCreateRoleRoute = AuthIamrolesCreateRoleRouteImport.update({
  id: '/iam/(roles)/create-role',
  path: '/iam/create-role',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthIampoliciesCreatePolicyRoute =
  AuthIampoliciesCreatePolicyRouteImport.update({
    id: '/iam/(policies)/create-policy',
    path: '/iam/create-policy',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthIaminstanceProfilesCreateInstanceProfileRoute =
  AuthIaminstanceProfilesCreateInstanceProfileRouteImport.update({
    id: '/iam/(instance-profiles)/create-instance-profile',
    path: '/iam/create-instance-profile',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEksclustersCreateClusterRoute =
  AuthEksclustersCreateClusterRouteImport.update({
    id: '/eks/(clusters)/create-cluster',
    path: '/eks/create-cluster',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEcsclustersTaskDefinitionsRoute =
  AuthEcsclustersTaskDefinitionsRouteImport.update({
    id: '/ecs/(clusters)/task-definitions',
    path: '/ecs/task-definitions',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEcsclustersRunTaskRoute = AuthEcsclustersRunTaskRouteImport.update({
  id: '/ecs/(clusters)/run-task',
  path: '/ecs/run-task',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEcsclustersRegisterTaskDefinitionRoute =
  AuthEcsclustersRegisterTaskDefinitionRouteImport.update({
    id: '/ecs/(clusters)/register-task-definition',
    path: '/ecs/register-task-definition',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEcsclustersCreateServiceRoute =
  AuthEcsclustersCreateServiceRouteImport.update({
    id: '/ecs/(clusters)/create-service',
    path: '/ecs/create-service',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2vpcCreateVpcRoute = AuthEc2vpcCreateVpcRouteImport.update({
  id: '/ec2/(vpc)/create-vpc',
  path: '/ec2/create-vpc',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEc2volumesCreateVolumeRoute =
  AuthEc2volumesCreateVolumeRouteImport.update({
    id: '/ec2/(volumes)/create-volume',
    path: '/ec2/create-volume',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2targetGroupsCreateTargetGroupRoute =
  AuthEc2targetGroupsCreateTargetGroupRouteImport.update({
    id: '/ec2/(target-groups)/create-target-group',
    path: '/ec2/create-target-group',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2subnetCreateSubnetRoute =
  AuthEc2subnetCreateSubnetRouteImport.update({
    id: '/ec2/(subnet)/create-subnet',
    path: '/ec2/create-subnet',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2snapshotsCreateSnapshotRoute =
  AuthEc2snapshotsCreateSnapshotRouteImport.update({
    id: '/ec2/(snapshots)/create-snapshot',
    path: '/ec2/create-snapshot',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2securityGroupsCreateSecurityGroupRoute =
  AuthEc2securityGroupsCreateSecurityGroupRouteImport.update({
    id: '/ec2/(security-groups)/create-security-group',
    path: '/ec2/create-security-group',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2routeTablesCreateRouteTableRoute =
  AuthEc2routeTablesCreateRouteTableRouteImport.update({
    id: '/ec2/(route-tables)/create-route-table',
    path: '/ec2/create-route-table',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2placementGroupsCreatePlacementGroupRoute =
  AuthEc2placementGroupsCreatePlacementGroupRouteImport.update({
    id: '/ec2/(placement-groups)/create-placement-group',
    path: '/ec2/create-placement-group',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2natGatewaysCreateNatGatewayRoute =
  AuthEc2natGatewaysCreateNatGatewayRouteImport.update({
    id: '/ec2/(nat-gateways)/create-nat-gateway',
    path: '/ec2/create-nat-gateway',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2loadBalancersCreateLoadBalancerRoute =
  AuthEc2loadBalancersCreateLoadBalancerRouteImport.update({
    id: '/ec2/(load-balancers)/create-load-balancer',
    path: '/ec2/create-load-balancer',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2keyImportKeyPairRoute = AuthEc2keyImportKeyPairRouteImport.update({
  id: '/ec2/(key)/import-key-pair',
  path: '/ec2/import-key-pair',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEc2keyCreateKeyPairRoute = AuthEc2keyCreateKeyPairRouteImport.update({
  id: '/ec2/(key)/create-key-pair',
  path: '/ec2/create-key-pair',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEc2internetGatewaysCreateInternetGatewayRoute =
  AuthEc2internetGatewaysCreateInternetGatewayRouteImport.update({
    id: '/ec2/(internet-gateways)/create-internet-gateway',
    path: '/ec2/create-internet-gateway',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2instancesRunInstancesRoute =
  AuthEc2instancesRunInstancesRouteImport.update({
    id: '/ec2/(instances)/run-instances',
    path: '/ec2/run-instances',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2elasticIpsAllocateAddressRoute =
  AuthEc2elasticIpsAllocateAddressRouteImport.update({
    id: '/ec2/(elastic-ips)/allocate-address',
    path: '/ec2/allocate-address',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthS3LsBucketRouteRoute = AuthS3LsBucketRouteRouteImport.update({
  id: '/s3/ls/$bucket',
  path: '/s3/ls/$bucket',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthS3LsBucketIndexRoute = AuthS3LsBucketIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthS3LsBucketRouteRoute,
} as any)
const AuthIamusersListUsersIndexRoute =
  AuthIamusersListUsersIndexRouteImport.update({
    id: '/iam/(users)/list-users/',
    path: '/iam/list-users/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthIamrolesListRolesIndexRoute =
  AuthIamrolesListRolesIndexRouteImport.update({
    id: '/iam/(roles)/list-roles/',
    path: '/iam/list-roles/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthIampoliciesListPoliciesIndexRoute =
  AuthIampoliciesListPoliciesIndexRouteImport.update({
    id: '/iam/(policies)/list-policies/',
    path: '/iam/list-policies/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthIaminstanceProfilesListInstanceProfilesIndexRoute =
  AuthIaminstanceProfilesListInstanceProfilesIndexRouteImport.update({
    id: '/iam/(instance-profiles)/list-instance-profiles/',
    path: '/iam/list-instance-profiles/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEksclustersListClustersIndexRoute =
  AuthEksclustersListClustersIndexRouteImport.update({
    id: '/eks/(clusters)/list-clusters/',
    path: '/eks/list-clusters/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEcsclustersListClustersIndexRoute =
  AuthEcsclustersListClustersIndexRouteImport.update({
    id: '/ecs/(clusters)/list-clusters/',
    path: '/ecs/list-clusters/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEcrrepositoriesListRepositoriesIndexRoute =
  AuthEcrrepositoriesListRepositoriesIndexRouteImport.update({
    id: '/ecr/(repositories)/list-repositories/',
    path: '/ecr/list-repositories/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2vpcDescribeVpcsIndexRoute =
  AuthEc2vpcDescribeVpcsIndexRouteImport.update({
    id: '/ec2/(vpc)/describe-vpcs/',
    path: '/ec2/describe-vpcs/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2volumesDescribeVolumesIndexRoute =
  AuthEc2volumesDescribeVolumesIndexRouteImport.update({
    id: '/ec2/(volumes)/describe-volumes/',
    path: '/ec2/describe-volumes/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2targetGroupsDescribeTargetGroupsIndexRoute =
  AuthEc2targetGroupsDescribeTargetGroupsIndexRouteImport.update({
    id: '/ec2/(target-groups)/describe-target-groups/',
    path: '/ec2/describe-target-groups/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2subnetDescribeSubnetsIndexRoute =
  AuthEc2subnetDescribeSubnetsIndexRouteImport.update({
    id: '/ec2/(subnet)/describe-subnets/',
    path: '/ec2/describe-subnets/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2snapshotsDescribeSnapshotsIndexRoute =
  AuthEc2snapshotsDescribeSnapshotsIndexRouteImport.update({
    id: '/ec2/(snapshots)/describe-snapshots/',
    path: '/ec2/describe-snapshots/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2securityGroupsDescribeSecurityGroupsIndexRoute =
  AuthEc2securityGroupsDescribeSecurityGroupsIndexRouteImport.update({
    id: '/ec2/(security-groups)/describe-security-groups/',
    path: '/ec2/describe-security-groups/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2routeTablesDescribeRouteTablesIndexRoute =
  AuthEc2routeTablesDescribeRouteTablesIndexRouteImport.update({
    id: '/ec2/(route-tables)/describe-route-tables/',
    path: '/ec2/describe-route-tables/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2placementGroupsDescribePlacementGroupsIndexRoute =
  AuthEc2placementGroupsDescribePlacementGroupsIndexRouteImport.update({
    id: '/ec2/(placement-groups)/describe-placement-groups/',
    path: '/ec2/describe-placement-groups/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2natGatewaysDescribeNatGatewaysIndexRoute =
  AuthEc2natGatewaysDescribeNatGatewaysIndexRouteImport.update({
    id: '/ec2/(nat-gateways)/describe-nat-gateways/',
    path: '/ec2/describe-nat-gateways/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2loadBalancersDescribeLoadBalancersIndexRoute =
  AuthEc2loadBalancersDescribeLoadBalancersIndexRouteImport.update({
    id: '/ec2/(load-balancers)/describe-load-balancers/',
    path: '/ec2/describe-load-balancers/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2keyDescribeKeyPairsIndexRoute =
  AuthEc2keyDescribeKeyPairsIndexRouteImport.update({
    id: '/ec2/(key)/describe-key-pairs/',
    path: '/ec2/describe-key-pairs/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2internetGatewaysDescribeInternetGatewaysIndexRoute =
  AuthEc2internetGatewaysDescribeInternetGatewaysIndexRouteImport.update({
    id: '/ec2/(internet-gateways)/describe-internet-gateways/',
    path: '/ec2/describe-internet-gateways/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2instancesDescribeInstancesIndexRoute =
  AuthEc2instancesDescribeInstancesIndexRouteImport.update({
    id: '/ec2/(instances)/describe-instances/',
    path: '/ec2/describe-instances/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2imagesDescribeImagesIndexRoute =
  AuthEc2imagesDescribeImagesIndexRouteImport.update({
    id: '/ec2/(images)/describe-images/',
    path: '/ec2/describe-images/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2elasticIpsDescribeAddressesIndexRoute =
  AuthEc2elasticIpsDescribeAddressesIndexRouteImport.update({
    id: '/ec2/(elastic-ips)/describe-addresses/',
    path: '/ec2/describe-addresses/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthS3LsBucketSplatRoute = AuthS3LsBucketSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthS3LsBucketRouteRoute,
} as any)
const AuthIamusersListUsersUserNameRoute =
  AuthIamusersListUsersUserNameRouteImport.update({
    id: '/iam/(users)/list-users/$userName',
    path: '/iam/list-users/$userName',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthIamrolesListRolesRoleNameRoute =
  AuthIamrolesListRolesRoleNameRouteImport.update({
    id: '/iam/(roles)/list-roles/$roleName',
    path: '/iam/list-roles/$roleName',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthIampoliciesListPoliciesPolicyArnRoute =
  AuthIampoliciesListPoliciesPolicyArnRouteImport.update({
    id: '/iam/(policies)/list-policies/$policyArn',
    path: '/iam/list-policies/$policyArn',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthIaminstanceProfilesListInstanceProfilesInstanceProfileNameRoute =
  AuthIaminstanceProfilesListInstanceProfilesInstanceProfileNameRouteImport.update(
    {
      id: '/iam/(instance-profiles)/list-instance-profiles/$instanceProfileName',
      path: '/iam/list-instance-profiles/$instanceProfileName',
      getParentRoute: () => AuthRouteRoute,
    } as any,
  )
const AuthEksclustersListClustersClusterNameRoute =
  AuthEksclustersListClustersClusterNameRouteImport.update({
    id: '/eks/(clusters)/list-clusters/$clusterName',
    path: '/eks/list-clusters/$clusterName',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEcsclustersListClustersClusterNameRoute =
  AuthEcsclustersListClustersClusterNameRouteImport.update({
    id: '/ecs/(clusters)/list-clusters/$clusterName',
    path: '/ecs/list-clusters/$clusterName',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEcrrepositoriesListRepositoriesIdRoute =
  AuthEcrrepositoriesListRepositoriesIdRouteImport.update({
    id: '/ecr/(repositories)/list-repositories/$id',
    path: '/ecr/list-repositories/$id',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2vpcDescribeVpcsIdRoute =
  AuthEc2vpcDescribeVpcsIdRouteImport.update({
    id: '/ec2/(vpc)/describe-vpcs/$id',
    path: '/ec2/describe-vpcs/$id',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2volumesModifyVolumeIdRoute =
  AuthEc2volumesModifyVolumeIdRouteImport.update({
    id: '/ec2/(volumes)/modify-volume/$id',
    path: '/ec2/modify-volume/$id',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2volumesDescribeVolumesIdRoute =
  AuthEc2volumesDescribeVolumesIdRouteImport.update({
    id: '/ec2/(volumes)/describe-volumes/$id',
    path: '/ec2/describe-volumes/$id',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2targetGroupsDescribeTargetGroupsIdRoute =
  AuthEc2targetGroupsDescribeTargetGroupsIdRouteImport.update({
    id: '/ec2/(target-groups)/describe-target-groups/$id',
    path: '/ec2/describe-target-groups/$id',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2subnetDescribeSubnetsIdRoute =
  AuthEc2subnetDescribeSubnetsIdRouteImport.update({
    id: '/ec2/(subnet)/describe-subnets/$id',
    path: '/ec2/describe-subnets/$id',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2snapshotsDescribeSnapshotsIdRoute =
  AuthEc2snapshotsDescribeSnapshotsIdRouteImport.update({
    id: '/ec2/(snapshots)/describe-snapshots/$id',
    path: '/ec2/describe-snapshots/$id',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2securityGroupsDescribeSecurityGroupsIdRoute =
  AuthEc2securityGroupsDescribeSecurityGroupsIdRouteImport.update({
    id: '/ec2/(security-groups)/describe-security-groups/$id',
    path: '/ec2/describe-security-groups/$id',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2routeTablesDescribeRouteTablesIdRoute =
  AuthEc2routeTablesDescribeRouteTablesIdRouteImport.update({
    id: '/ec2/(route-tables)/describe-route-tables/$id',
    path: '/ec2/describe-route-tables/$id',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2placementGroupsDescribePlacementGroupsIdRoute =
  AuthEc2placementGroupsDescribePlacementGroupsIdRouteImport.update({
    id: '/ec2/(placement-groups)/describe-placement-groups/$id',
    path: '/ec2/describe-placement-groups/$id',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2natGatewaysDescribeNatGatewaysIdRoute =
  AuthEc2natGatewaysDescribeNatGatewaysIdRouteImport.update({
    id: '/ec2/(nat-gateways)/describe-nat-gateways/$id',
    path: '/ec2/describe-nat-gateways/$id',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2loadBalancersDescribeLoadBalancersIdRoute =
  AuthEc2loadBalancersDescribeLoadBalancersIdRouteImport.update({
    id: '/ec2/(load-balancers)/describe-load-balancers/$id',
    path: '/ec2/describe-load-balancers/$id',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2keyDescribeKeyPairsIdRoute =
  AuthEc2keyDescribeKeyPairsIdRouteImport.update({
    id: '/ec2/(key)/describe-key-pairs/$id',
    path: '/ec2/describe-key-pairs/$id',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2internetGatewaysDescribeInternetGatewaysIdRoute =
  AuthEc2internetGatewaysDescribeInternetGatewaysIdRouteImport.update({
    id: '/ec2/(internet-gateways)/describe-internet-gateways/$id',
    path: '/ec2/describe-internet-gateways/$id',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2instancesDescribeInstancesIdRoute =
  AuthEc2instancesDescribeInstancesIdRouteImport.update({
    id: '/ec2/(instances)/describe-instances/$id',
    path: '/ec2/describe-instances/$id',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2imagesDescribeImagesIdRoute =
  AuthEc2imagesDescribeImagesIdRouteImport.update({
    id: '/ec2/(images)/describe-images/$id',
    path: '/ec2/describe-images/$id',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEc2elasticIpsDescribeAddressesIdRoute =
  AuthEc2elasticIpsDescribeAddressesIdRouteImport.update({
    id: '/ec2/(elastic-ips)/describe-addresses/$id',
    path: '/ec2/describe-addresses/$id',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEcsclustersListClustersClusterNameTasksTaskIdRoute =
  AuthEcsclustersListClustersClusterNameTasksTaskIdRouteImport.update({
    id: '/ecs/(clusters)/list-clusters/$clusterName_/tasks/$taskId',
    path: '/ecs/list-clusters/$clusterName/tasks/$taskId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEcsclustersListClustersClusterNameServicesServiceNameRoute =
  AuthEcsclustersListClustersClusterNameServicesServiceNameRouteImport.update({
    id: '/ecs/(clusters)/list-clusters/$clusterName_/services/$serviceName',
    path: '/ecs/list-clusters/$clusterName/services/$serviceName',
    getParentRoute: () => AuthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/nodes': typeof AuthNodesRoute
  '/s3/service-metrics': typeof AuthS3ServiceMetricsRoute
  '/s3/ls/$bucket': typeof AuthS3LsBucketRouteRouteWithChildren
  '/ec2/allocate-address': typeof AuthEc2elasticIpsAllocateAddressRoute
  '/ec2/run-instances': typeof AuthEc2instancesRunInstancesRoute
  '/ec2/create-internet-gateway': typeof AuthEc2internetGatewaysCreateInternetGatewayRoute
  '/ec2/create-key-pair': typeof AuthEc2keyCreateKeyPairRoute
  '/ec2/import-key-pair': typeof AuthEc2keyImportKeyPairRoute
  '/ec2/create-load-balancer': typeof AuthEc2loadBalancersCreateLoadBalancerRoute
  '/ec2/create-nat-gateway': typeof AuthEc2natGatewaysCreateNatGatewayRoute
  '/ec2/create-placement-group': typeof AuthEc2placementGroupsCreatePlacementGroupRoute
  '/ec2/create-route-table': typeof AuthEc2routeTablesCreateRouteTableRoute
  '/ec2/create-security-group': typeof AuthEc2securityGroupsCreateSecurityGroupRoute
  '/ec2/create-snapshot': typeof AuthEc2snapshotsCreateSnapshotRoute
  '/ec2/create-subnet': typeof AuthEc2subnetCreateSubnetRoute
  '/ec2/create-target-group': typeof AuthEc2targetGroupsCreateTargetGroupRoute
  '/ec2/create-volume': typeof AuthEc2volumesCreateVolumeRoute
  '/ec2/create-vpc': typeof AuthEc2vpcCreateVpcRoute
  '/ecs/create-service': typeof AuthEcsclustersCreateServiceRoute
  '/ecs/register-task-definition': typeof AuthEcsclustersRegisterTaskDefinitionRoute
  '/ecs/run-task': typeof AuthEcsclustersRunTaskRoute
  '/ecs/task-definitions': typeof AuthEcsclustersTaskDefinitionsRoute
  '/eks/create-cluster': typeof AuthEksclustersCreateClusterRoute
  '/iam/create-instance-profile': typeof AuthIaminstanceProfilesCreateInstanceProfileRoute
  '/iam/create-policy': typeof AuthIampoliciesCreatePolicyRoute
  '/iam/create-role': typeof AuthIamrolesCreateRoleRoute
  '/iam/create-user': typeof AuthIamusersCreateUserRoute
  '/s3/create-bucket': typeof AuthS3bucketsCreateBucketRoute
  '/s3/ls/': typeof AuthS3LsIndexRoute
  '/ec2/describe-addresses/$id': typeof AuthEc2elasticIpsDescribeAddressesIdRoute
  '/ec2/describe-images/$id': typeof AuthEc2imagesDescribeImagesIdRoute
  '/ec2/describe-instances/$id': typeof AuthEc2instancesDescribeInstancesIdRoute
  '/ec2/describe-internet-gateways/$id': typeof AuthEc2internetGatewaysDescribeInternetGatewaysIdRoute
  '/ec2/describe-key-pairs/$id': typeof AuthEc2keyDescribeKeyPairsIdRoute
  '/ec2/describe-load-balancers/$id': typeof AuthEc2loadBalancersDescribeLoadBalancersIdRoute
  '/ec2/describe-nat-gateways/$id': typeof AuthEc2natGatewaysDescribeNatGatewaysIdRoute
  '/ec2/describe-placement-groups/$id': typeof AuthEc2placementGroupsDescribePlacementGroupsIdRoute
  '/ec2/describe-route-tables/$id': typeof AuthEc2routeTablesDescribeRouteTablesIdRoute
  '/ec2/describe-security-groups/$id': typeof AuthEc2securityGroupsDescribeSecurityGroupsIdRoute
  '/ec2/describe-snapshots/$id': typeof AuthEc2snapshotsDescribeSnapshotsIdRoute
  '/ec2/describe-subnets/$id': typeof AuthEc2subnetDescribeSubnetsIdRoute
  '/ec2/describe-target-groups/$id': typeof AuthEc2targetGroupsDescribeTargetGroupsIdRoute
  '/ec2/describe-volumes/$id': typeof AuthEc2volumesDescribeVolumesIdRoute
  '/ec2/modify-volume/$id': typeof AuthEc2volumesModifyVolumeIdRoute
  '/ec2/describe-vpcs/$id': typeof AuthEc2vpcDescribeVpcsIdRoute
  '/ecr/list-repositories/$id': typeof AuthEcrrepositoriesListRepositoriesIdRoute
  '/ecs/list-clusters/$clusterName': typeof AuthEcsclustersListClustersClusterNameRoute
  '/eks/list-clusters/$clusterName': typeof AuthEksclustersListClustersClusterNameRoute
  '/iam/list-instance-profiles/$instanceProfileName': typeof AuthIaminstanceProfilesListInstanceProfilesInstanceProfileNameRoute
  '/iam/list-policies/$policyArn': typeof AuthIampoliciesListPoliciesPolicyArnRoute
  '/iam/list-roles/$roleName': typeof AuthIamrolesListRolesRoleNameRoute
  '/iam/list-users/$userName': typeof AuthIamusersListUsersUserNameRoute
  '/s3/ls/$bucket/$': typeof AuthS3LsBucketSplatRoute
  '/ec2/describe-addresses/': typeof AuthEc2elasticIpsDescribeAddressesIndexRoute
  '/ec2/describe-images/': typeof AuthEc2imagesDescribeImagesIndexRoute
  '/ec2/describe-instances/': typeof AuthEc2instancesDescribeInstancesIndexRoute
  '/ec2/describe-internet-gateways/': typeof AuthEc2internetGatewaysDescribeInternetGatewaysIndexRoute
  '/ec2/describe-key-pairs/': typeof AuthEc2keyDescribeKeyPairsIndexRoute
  '/ec2/describe-load-balancers/': typeof AuthEc2loadBalancersDescribeLoadBalancersIndexRoute
  '/ec2/describe-nat-gateways/': typeof AuthEc2natGatewaysDescribeNatGatewaysIndexRoute
  '/ec2/describe-placement-groups/': typeof AuthEc2placementGroupsDescribePlacementGroupsIndexRoute
  '/ec2/describe-route-tables/': typeof AuthEc2routeTablesDescribeRouteTablesIndexRoute
  '/ec2/describe-security-groups/': typeof AuthEc2securityGroupsDescribeSecurityGroupsIndexRoute
  '/ec2/describe-snapshots/': typeof AuthEc2snapshotsDescribeSnapshotsIndexRoute
  '/ec2/describe-subnets/': typeof AuthEc2subnetDescribeSubnetsIndexRoute
  '/ec2/describe-target-groups/': typeof AuthEc2targetGroupsDescribeTargetGroupsIndexRoute
  '/ec2/describe-volumes/': typeof AuthEc2volumesDescribeVolumesIndexRoute
  '/ec2/describe-vpcs/': typeof AuthEc2vpcDescribeVpcsIndexRoute
  '/ecr/list-repositories/': typeof AuthEcrrepositoriesListRepositoriesIndexRoute
  '/ecs/list-clusters/': typeof AuthEcsclustersListClustersIndexRoute
  '/eks/list-clusters/': typeof AuthEksclustersListClustersIndexRoute
  '/iam/list-instance-profiles/': typeof AuthIaminstanceProfilesListInstanceProfilesIndexRoute
  '/iam/list-policies/': typeof AuthIampoliciesListPoliciesIndexRoute
  '/iam/list-roles/': typeof AuthIamrolesListRolesIndexRoute
  '/iam/list-users/': typeof AuthIamusersListUsersIndexRoute
  '/s3/ls/$bucket/': typeof AuthS3LsBucketIndexRoute
  '/ecs/list-clusters/$clusterName/services/$serviceName': typeof AuthEcsclustersListClustersClusterNameServicesServiceNameRoute
  '/ecs/list-clusters/$clusterName/tasks/$taskId': typeof AuthEcsclustersListClustersClusterNameTasksTaskIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/nodes': typeof AuthNodesRoute
  '/': typeof AuthIndexRoute
  '/s3/service-metrics': typeof AuthS3ServiceMetricsRoute
  '/ec2/allocate-address': typeof AuthEc2elasticIpsAllocateAddressRoute
  '/ec2/run-instances': typeof AuthEc2instancesRunInstancesRoute
  '/ec2/create-internet-gateway': typeof AuthEc2internetGatewaysCreateInternetGatewayRoute
  '/ec2/create-key-pair': typeof AuthEc2keyCreateKeyPairRoute
  '/ec2/import-key-pair': typeof AuthEc2keyImportKeyPairRoute
  '/ec2/create-load-balancer': typeof AuthEc2loadBalancersCreateLoadBalancerRoute
  '/ec2/create-nat-gateway': typeof AuthEc2natGatewaysCreateNatGatewayRoute
  '/ec2/create-placement-group': typeof AuthEc2placementGroupsCreatePlacementGroupRoute
  '/ec2/create-route-table': typeof AuthEc2routeTablesCreateRouteTableRoute
  '/ec2/create-security-group': typeof AuthEc2securityGroupsCreateSecurityGroupRoute
  '/ec2/create-snapshot': typeof AuthEc2snapshotsCreateSnapshotRoute
  '/ec2/create-subnet': typeof AuthEc2subnetCreateSubnetRoute
  '/ec2/create-target-group': typeof AuthEc2targetGroupsCreateTargetGroupRoute
  '/ec2/create-volume': typeof AuthEc2volumesCreateVolumeRoute
  '/ec2/create-vpc': typeof AuthEc2vpcCreateVpcRoute
  '/ecs/create-service': typeof AuthEcsclustersCreateServiceRoute
  '/ecs/register-task-definition': typeof AuthEcsclustersRegisterTaskDefinitionRoute
  '/ecs/run-task': typeof AuthEcsclustersRunTaskRoute
  '/ecs/task-definitions': typeof AuthEcsclustersTaskDefinitionsRoute
  '/eks/create-cluster': typeof AuthEksclustersCreateClusterRoute
  '/iam/create-instance-profile': typeof AuthIaminstanceProfilesCreateInstanceProfileRoute
  '/iam/create-policy': typeof AuthIampoliciesCreatePolicyRoute
  '/iam/create-role': typeof AuthIamrolesCreateRoleRoute
  '/iam/create-user': typeof AuthIamusersCreateUserRoute
  '/s3/create-bucket': typeof AuthS3bucketsCreateBucketRoute
  '/s3/ls': typeof AuthS3LsIndexRoute
  '/ec2/describe-addresses/$id': typeof AuthEc2elasticIpsDescribeAddressesIdRoute
  '/ec2/describe-images/$id': typeof AuthEc2imagesDescribeImagesIdRoute
  '/ec2/describe-instances/$id': typeof AuthEc2instancesDescribeInstancesIdRoute
  '/ec2/describe-internet-gateways/$id': typeof AuthEc2internetGatewaysDescribeInternetGatewaysIdRoute
  '/ec2/describe-key-pairs/$id': typeof AuthEc2keyDescribeKeyPairsIdRoute
  '/ec2/describe-load-balancers/$id': typeof AuthEc2loadBalancersDescribeLoadBalancersIdRoute
  '/ec2/describe-nat-gateways/$id': typeof AuthEc2natGatewaysDescribeNatGatewaysIdRoute
  '/ec2/describe-placement-groups/$id': typeof AuthEc2placementGroupsDescribePlacementGroupsIdRoute
  '/ec2/describe-route-tables/$id': typeof AuthEc2routeTablesDescribeRouteTablesIdRoute
  '/ec2/describe-security-groups/$id': typeof AuthEc2securityGroupsDescribeSecurityGroupsIdRoute
  '/ec2/describe-snapshots/$id': typeof AuthEc2snapshotsDescribeSnapshotsIdRoute
  '/ec2/describe-subnets/$id': typeof AuthEc2subnetDescribeSubnetsIdRoute
  '/ec2/describe-target-groups/$id': typeof AuthEc2targetGroupsDescribeTargetGroupsIdRoute
  '/ec2/describe-volumes/$id': typeof AuthEc2volumesDescribeVolumesIdRoute
  '/ec2/modify-volume/$id': typeof AuthEc2volumesModifyVolumeIdRoute
  '/ec2/describe-vpcs/$id': typeof AuthEc2vpcDescribeVpcsIdRoute
  '/ecr/list-repositories/$id': typeof AuthEcrrepositoriesListRepositoriesIdRoute
  '/ecs/list-clusters/$clusterName': typeof AuthEcsclustersListClustersClusterNameRoute
  '/eks/list-clusters/$clusterName': typeof AuthEksclustersListClustersClusterNameRoute
  '/iam/list-instance-profiles/$instanceProfileName': typeof AuthIaminstanceProfilesListInstanceProfilesInstanceProfileNameRoute
  '/iam/list-policies/$policyArn': typeof AuthIampoliciesListPoliciesPolicyArnRoute
  '/iam/list-roles/$roleName': typeof AuthIamrolesListRolesRoleNameRoute
  '/iam/list-users/$userName': typeof AuthIamusersListUsersUserNameRoute
  '/s3/ls/$bucket/$': typeof AuthS3LsBucketSplatRoute
  '/ec2/describe-addresses': typeof AuthEc2elasticIpsDescribeAddressesIndexRoute
  '/ec2/describe-images': typeof AuthEc2imagesDescribeImagesIndexRoute
  '/ec2/describe-instances': typeof AuthEc2instancesDescribeInstancesIndexRoute
  '/ec2/describe-internet-gateways': typeof AuthEc2internetGatewaysDescribeInternetGatewaysIndexRoute
  '/ec2/describe-key-pairs': typeof AuthEc2keyDescribeKeyPairsIndexRoute
  '/ec2/describe-load-balancers': typeof AuthEc2loadBalancersDescribeLoadBalancersIndexRoute
  '/ec2/describe-nat-gateways': typeof AuthEc2natGatewaysDescribeNatGatewaysIndexRoute
  '/ec2/describe-placement-groups': typeof AuthEc2placementGroupsDescribePlacementGroupsIndexRoute
  '/ec2/describe-route-tables': typeof AuthEc2routeTablesDescribeRouteTablesIndexRoute
  '/ec2/describe-security-groups': typeof AuthEc2securityGroupsDescribeSecurityGroupsIndexRoute
  '/ec2/describe-snapshots': typeof AuthEc2snapshotsDescribeSnapshotsIndexRoute
  '/ec2/describe-subnets': typeof AuthEc2subnetDescribeSubnetsIndexRoute
  '/ec2/describe-target-groups': typeof AuthEc2targetGroupsDescribeTargetGroupsIndexRoute
  '/ec2/describe-volumes': typeof AuthEc2volumesDescribeVolumesIndexRoute
  '/ec2/describe-vpcs': typeof AuthEc2vpcDescribeVpcsIndexRoute
  '/ecr/list-repositories': typeof AuthEcrrepositoriesListRepositoriesIndexRoute
  '/ecs/list-clusters': typeof AuthEcsclustersListClustersIndexRoute
  '/eks/list-clusters': typeof AuthEksclustersListClustersIndexRoute
  '/iam/list-instance-profiles': typeof AuthIaminstanceProfilesListInstanceProfilesIndexRoute
  '/iam/list-policies': typeof AuthIampoliciesListPoliciesIndexRoute
  '/iam/list-roles': typeof AuthIamrolesListRolesIndexRoute
  '/iam/list-users': typeof AuthIamusersListUsersIndexRoute
  '/s3/ls/$bucket': typeof AuthS3LsBucketIndexRoute
  '/ecs/list-clusters/$clusterName/services/$serviceName': typeof AuthEcsclustersListClustersClusterNameServicesServiceNameRoute
  '/ecs/list-clusters/$clusterName/tasks/$taskId': typeof AuthEcsclustersListClustersClusterNameTasksTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/nodes': typeof AuthNodesRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/s3/service-metrics': typeof AuthS3ServiceMetricsRoute
  '/_auth/s3/ls/$bucket': typeof AuthS3LsBucketRouteRouteWithChildren
  '/_auth/ec2/(elastic-ips)/allocate-address': typeof AuthEc2elasticIpsAllocateAddressRoute
  '/_auth/ec2/(instances)/run-instances': typeof AuthEc2instancesRunInstancesRoute
  '/_auth/ec2/(internet-gateways)/create-internet-gateway': typeof AuthEc2internetGatewaysCreateInternetGatewayRoute
  '/_auth/ec2/(key)/create-key-pair': typeof AuthEc2keyCreateKeyPairRoute
  '/_auth/ec2/(key)/import-key-pair': typeof AuthEc2keyImportKeyPairRoute
  '/_auth/ec2/(load-balancers)/create-load-balancer': typeof AuthEc2loadBalancersCreateLoadBalancerRoute
  '/_auth/ec2/(nat-gateways)/create-nat-gateway': typeof AuthEc2natGatewaysCreateNatGatewayRoute
  '/_auth/ec2/(placement-groups)/create-placement-group': typeof AuthEc2placementGroupsCreatePlacementGroupRoute
  '/_auth/ec2/(route-tables)/create-route-table': typeof AuthEc2routeTablesCreateRouteTableRoute
  '/_auth/ec2/(security-groups)/create-security-group': typeof AuthEc2securityGroupsCreateSecurityGroupRoute
  '/_auth/ec2/(snapshots)/create-snapshot': typeof AuthEc2snapshotsCreateSnapshotRoute
  '/_auth/ec2/(subnet)/create-subnet': typeof AuthEc2subnetCreateSubnetRoute
  '/_auth/ec2/(target-groups)/create-target-group': typeof AuthEc2targetGroupsCreateTargetGroupRoute
  '/_auth/ec2/(volumes)/create-volume': typeof AuthEc2volumesCreateVolumeRoute
  '/_auth/ec2/(vpc)/create-vpc': typeof AuthEc2vpcCreateVpcRoute
  '/_auth/ecs/(clusters)/create-service': typeof AuthEcsclustersCreateServiceRoute
  '/_auth/ecs/(clusters)/register-task-definition': typeof AuthEcsclustersRegisterTaskDefinitionRoute
  '/_auth/ecs/(clusters)/run-task': typeof AuthEcsclustersRunTaskRoute
  '/_auth/ecs/(clusters)/task-definitions': typeof AuthEcsclustersTaskDefinitionsRoute
  '/_auth/eks/(clusters)/create-cluster': typeof AuthEksclustersCreateClusterRoute
  '/_auth/iam/(instance-profiles)/create-instance-profile': typeof AuthIaminstanceProfilesCreateInstanceProfileRoute
  '/_auth/iam/(policies)/create-policy': typeof AuthIampoliciesCreatePolicyRoute
  '/_auth/iam/(roles)/create-role': typeof AuthIamrolesCreateRoleRoute
  '/_auth/iam/(users)/create-user': typeof AuthIamusersCreateUserRoute
  '/_auth/s3/(buckets)/create-bucket': typeof AuthS3bucketsCreateBucketRoute
  '/_auth/s3/ls/': typeof AuthS3LsIndexRoute
  '/_auth/ec2/(elastic-ips)/describe-addresses/$id': typeof AuthEc2elasticIpsDescribeAddressesIdRoute
  '/_auth/ec2/(images)/describe-images/$id': typeof AuthEc2imagesDescribeImagesIdRoute
  '/_auth/ec2/(instances)/describe-instances/$id': typeof AuthEc2instancesDescribeInstancesIdRoute
  '/_auth/ec2/(internet-gateways)/describe-internet-gateways/$id': typeof AuthEc2internetGatewaysDescribeInternetGatewaysIdRoute
  '/_auth/ec2/(key)/describe-key-pairs/$id': typeof AuthEc2keyDescribeKeyPairsIdRoute
  '/_auth/ec2/(load-balancers)/describe-load-balancers/$id': typeof AuthEc2loadBalancersDescribeLoadBalancersIdRoute
  '/_auth/ec2/(nat-gateways)/describe-nat-gateways/$id': typeof AuthEc2natGatewaysDescribeNatGatewaysIdRoute
  '/_auth/ec2/(placement-groups)/describe-placement-groups/$id': typeof AuthEc2placementGroupsDescribePlacementGroupsIdRoute
  '/_auth/ec2/(route-tables)/describe-route-tables/$id': typeof AuthEc2routeTablesDescribeRouteTablesIdRoute
  '/_auth/ec2/(security-groups)/describe-security-groups/$id': typeof AuthEc2securityGroupsDescribeSecurityGroupsIdRoute
  '/_auth/ec2/(snapshots)/describe-snapshots/$id': typeof AuthEc2snapshotsDescribeSnapshotsIdRoute
  '/_auth/ec2/(subnet)/describe-subnets/$id': typeof AuthEc2subnetDescribeSubnetsIdRoute
  '/_auth/ec2/(target-groups)/describe-target-groups/$id': typeof AuthEc2targetGroupsDescribeTargetGroupsIdRoute
  '/_auth/ec2/(volumes)/describe-volumes/$id': typeof AuthEc2volumesDescribeVolumesIdRoute
  '/_auth/ec2/(volumes)/modify-volume/$id': typeof AuthEc2volumesModifyVolumeIdRoute
  '/_auth/ec2/(vpc)/describe-vpcs/$id': typeof AuthEc2vpcDescribeVpcsIdRoute
  '/_auth/ecr/(repositories)/list-repositories/$id': typeof AuthEcrrepositoriesListRepositoriesIdRoute
  '/_auth/ecs/(clusters)/list-clusters/$clusterName': typeof AuthEcsclustersListClustersClusterNameRoute
  '/_auth/eks/(clusters)/list-clusters/$clusterName': typeof AuthEksclustersListClustersClusterNameRoute
  '/_auth/iam/(instance-profiles)/list-instance-profiles/$instanceProfileName': typeof AuthIaminstanceProfilesListInstanceProfilesInstanceProfileNameRoute
  '/_auth/iam/(policies)/list-policies/$policyArn': typeof AuthIampoliciesListPoliciesPolicyArnRoute
  '/_auth/iam/(roles)/list-roles/$roleName': typeof AuthIamrolesListRolesRoleNameRoute
  '/_auth/iam/(users)/list-users/$userName': typeof AuthIamusersListUsersUserNameRoute
  '/_auth/s3/ls/$bucket/$': typeof AuthS3LsBucketSplatRoute
  '/_auth/ec2/(elastic-ips)/describe-addresses/': typeof AuthEc2elasticIpsDescribeAddressesIndexRoute
  '/_auth/ec2/(images)/describe-images/': typeof AuthEc2imagesDescribeImagesIndexRoute
  '/_auth/ec2/(instances)/describe-instances/': typeof AuthEc2instancesDescribeInstancesIndexRoute
  '/_auth/ec2/(internet-gateways)/describe-internet-gateways/': typeof AuthEc2internetGatewaysDescribeInternetGatewaysIndexRoute
  '/_auth/ec2/(key)/describe-key-pairs/': typeof AuthEc2keyDescribeKeyPairsIndexRoute
  '/_auth/ec2/(load-balancers)/describe-load-balancers/': typeof AuthEc2loadBalancersDescribeLoadBalancersIndexRoute
  '/_auth/ec2/(nat-gateways)/describe-nat-gateways/': typeof AuthEc2natGatewaysDescribeNatGatewaysIndexRoute
  '/_auth/ec2/(placement-groups)/describe-placement-groups/': typeof AuthEc2placementGroupsDescribePlacementGroupsIndexRoute
  '/_auth/ec2/(route-tables)/describe-route-tables/': typeof AuthEc2routeTablesDescribeRouteTablesIndexRoute
  '/_auth/ec2/(security-groups)/describe-security-groups/': typeof AuthEc2securityGroupsDescribeSecurityGroupsIndexRoute
  '/_auth/ec2/(snapshots)/describe-snapshots/': typeof AuthEc2snapshotsDescribeSnapshotsIndexRoute
  '/_auth/ec2/(subnet)/describe-subnets/': typeof AuthEc2subnetDescribeSubnetsIndexRoute
  '/_auth/ec2/(target-groups)/describe-target-groups/': typeof AuthEc2targetGroupsDescribeTargetGroupsIndexRoute
  '/_auth/ec2/(volumes)/describe-volumes/': typeof AuthEc2volumesDescribeVolumesIndexRoute
  '/_auth/ec2/(vpc)/describe-vpcs/': typeof AuthEc2vpcDescribeVpcsIndexRoute
  '/_auth/ecr/(repositories)/list-repositories/': typeof AuthEcrrepositoriesListRepositoriesIndexRoute
  '/_auth/ecs/(clusters)/list-clusters/': typeof AuthEcsclustersListClustersIndexRoute
  '/_auth/eks/(clusters)/list-clusters/': typeof AuthEksclustersListClustersIndexRoute
  '/_auth/iam/(instance-profiles)/list-instance-profiles/': typeof AuthIaminstanceProfilesListInstanceProfilesIndexRoute
  '/_auth/iam/(policies)/list-policies/': typeof AuthIampoliciesListPoliciesIndexRoute
  '/_auth/iam/(roles)/list-roles/': typeof AuthIamrolesListRolesIndexRoute
  '/_auth/iam/(users)/list-users/': typeof AuthIamusersListUsersIndexRoute
  '/_auth/s3/ls/$bucket/': typeof AuthS3LsBucketIndexRoute
  '/_auth/ecs/(clusters)/list-clusters/$clusterName_/services/$serviceName': typeof AuthEcsclustersListClustersClusterNameServicesServiceNameRoute
  '/_auth/ecs/(clusters)/list-clusters/$clusterName_/tasks/$taskId': typeof AuthEcsclustersListClustersClusterNameTasksTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/nodes'
    | '/s3/service-metrics'
    | '/s3/ls/$bucket'
    | '/ec2/allocate-address'
    | '/ec2/run-instances'
    | '/ec2/create-internet-gateway'
    | '/ec2/create-key-pair'
    | '/ec2/import-key-pair'
    | '/ec2/create-load-balancer'
    | '/ec2/create-nat-gateway'
    | '/ec2/create-placement-group'
    | '/ec2/create-route-table'
    | '/ec2/create-security-group'
    | '/ec2/create-snapshot'
    | '/ec2/create-subnet'
    | '/ec2/create-target-group'
    | '/ec2/create-volume'
    | '/ec2/create-vpc'
    | '/ecs/create-service'
    | '/ecs/register-task-definition'
    | '/ecs/run-task'
    | '/ecs/task-definitions'
    | '/eks/create-cluster'
    | '/iam/create-instance-profile'
    | '/iam/create-policy'
    | '/iam/create-role'
    | '/iam/create-user'
    | '/s3/create-bucket'
    | '/s3/ls/'
    | '/ec2/describe-addresses/$id'
    | '/ec2/describe-images/$id'
    | '/ec2/describe-instances/$id'
    | '/ec2/describe-internet-gateways/$id'
    | '/ec2/describe-key-pairs/$id'
    | '/ec2/describe-load-balancers/$id'
    | '/ec2/describe-nat-gateways/$id'
    | '/ec2/describe-placement-groups/$id'
    | '/ec2/describe-route-tables/$id'
    | '/ec2/describe-security-groups/$id'
    | '/ec2/describe-snapshots/$id'
    | '/ec2/describe-subnets/$id'
    | '/ec2/describe-target-groups/$id'
    | '/ec2/describe-volumes/$id'
    | '/ec2/modify-volume/$id'
    | '/ec2/describe-vpcs/$id'
    | '/ecr/list-repositories/$id'
    | '/ecs/list-clusters/$clusterName'
    | '/eks/list-clusters/$clusterName'
    | '/iam/list-instance-profiles/$instanceProfileName'
    | '/iam/list-policies/$policyArn'
    | '/iam/list-roles/$roleName'
    | '/iam/list-users/$userName'
    | '/s3/ls/$bucket/$'
    | '/ec2/describe-addresses/'
    | '/ec2/describe-images/'
    | '/ec2/describe-instances/'
    | '/ec2/describe-internet-gateways/'
    | '/ec2/describe-key-pairs/'
    | '/ec2/describe-load-balancers/'
    | '/ec2/describe-nat-gateways/'
    | '/ec2/describe-placement-groups/'
    | '/ec2/describe-route-tables/'
    | '/ec2/describe-security-groups/'
    | '/ec2/describe-snapshots/'
    | '/ec2/describe-subnets/'
    | '/ec2/describe-target-groups/'
    | '/ec2/describe-volumes/'
    | '/ec2/describe-vpcs/'
    | '/ecr/list-repositories/'
    | '/ecs/list-clusters/'
    | '/eks/list-clusters/'
    | '/iam/list-instance-profiles/'
    | '/iam/list-policies/'
    | '/iam/list-roles/'
    | '/iam/list-users/'
    | '/s3/ls/$bucket/'
    | '/ecs/list-clusters/$clusterName/services/$serviceName'
    | '/ecs/list-clusters/$clusterName/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/nodes'
    | '/'
    | '/s3/service-metrics'
    | '/ec2/allocate-address'
    | '/ec2/run-instances'
    | '/ec2/create-internet-gateway'
    | '/ec2/create-key-pair'
    | '/ec2/import-key-pair'
    | '/ec2/create-load-balancer'
    | '/ec2/create-nat-gateway'
    | '/ec2/create-placement-group'
    | '/ec2/create-route-table'
    | '/ec2/create-security-group'
    | '/ec2/create-snapshot'
    | '/ec2/create-subnet'
    | '/ec2/create-target-group'
    | '/ec2/create-volume'
    | '/ec2/create-vpc'
    | '/ecs/create-service'
    | '/ecs/register-task-definition'
    | '/ecs/run-task'
    | '/ecs/task-definitions'
    | '/eks/create-cluster'
    | '/iam/create-instance-profile'
    | '/iam/create-policy'
    | '/iam/create-role'
    | '/iam/create-user'
    | '/s3/create-bucket'
    | '/s3/ls'
    | '/ec2/describe-addresses/$id'
    | '/ec2/describe-images/$id'
    | '/ec2/describe-instances/$id'
    | '/ec2/describe-internet-gateways/$id'
    | '/ec2/describe-key-pairs/$id'
    | '/ec2/describe-load-balancers/$id'
    | '/ec2/describe-nat-gateways/$id'
    | '/ec2/describe-placement-groups/$id'
    | '/ec2/describe-route-tables/$id'
    | '/ec2/describe-security-groups/$id'
    | '/ec2/describe-snapshots/$id'
    | '/ec2/describe-subnets/$id'
    | '/ec2/describe-target-groups/$id'
    | '/ec2/describe-volumes/$id'
    | '/ec2/modify-volume/$id'
    | '/ec2/describe-vpcs/$id'
    | '/ecr/list-repositories/$id'
    | '/ecs/list-clusters/$clusterName'
    | '/eks/list-clusters/$clusterName'
    | '/iam/list-instance-profiles/$instanceProfileName'
    | '/iam/list-policies/$policyArn'
    | '/iam/list-roles/$roleName'
    | '/iam/list-users/$userName'
    | '/s3/ls/$bucket/$'
    | '/ec2/describe-addresses'
    | '/ec2/describe-images'
    | '/ec2/describe-instances'
    | '/ec2/describe-internet-gateways'
    | '/ec2/describe-key-pairs'
    | '/ec2/describe-load-balancers'
    | '/ec2/describe-nat-gateways'
    | '/ec2/describe-placement-groups'
    | '/ec2/describe-route-tables'
    | '/ec2/describe-security-groups'
    | '/ec2/describe-snapshots'
    | '/ec2/describe-subnets'
    | '/ec2/describe-target-groups'
    | '/ec2/describe-volumes'
    | '/ec2/describe-vpcs'
    | '/ecr/list-repositories'
    | '/ecs/list-clusters'
    | '/eks/list-clusters'
    | '/iam/list-instance-profiles'
    | '/iam/list-policies'
    | '/iam/list-roles'
    | '/iam/list-users'
    | '/s3/ls/$bucket'
    | '/ecs/list-clusters/$clusterName/services/$serviceName'
    | '/ecs/list-clusters/$clusterName/tasks/$taskId'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/nodes'
    | '/_auth/'
    | '/_auth/s3/service-metrics'
    | '/_auth/s3/ls/$bucket'
    | '/_auth/ec2/(elastic-ips)/allocate-address'
    | '/_auth/ec2/(instances)/run-instances'
    | '/_auth/ec2/(internet-gateways)/create-internet-gateway'
    | '/_auth/ec2/(key)/create-key-pair'
    | '/_auth/ec2/(key)/import-key-pair'
    | '/_auth/ec2/(load-balancers)/create-load-balancer'
    | '/_auth/ec2/(nat-gateways)/create-nat-gateway'
    | '/_auth/ec2/(placement-groups)/create-placement-group'
    | '/_auth/ec2/(route-tables)/create-route-table'
    | '/_auth/ec2/(security-groups)/create-security-group'
    | '/_auth/ec2/(snapshots)/create-snapshot'
    | '/_auth/ec2/(subnet)/create-subnet'
    | '/_auth/ec2/(target-groups)/create-target-group'
    | '/_auth/ec2/(volumes)/create-volume'
    | '/_auth/ec2/(vpc)/create-vpc'
    | '/_auth/ecs/(clusters)/create-service'
    | '/_auth/ecs/(clusters)/register-task-definition'
    | '/_auth/ecs/(clusters)/run-task'
    | '/_auth/ecs/(clusters)/task-definitions'
    | '/_auth/eks/(clusters)/create-cluster'
    | '/_auth/iam/(instance-profiles)/create-instance-profile'
    | '/_auth/iam/(policies)/create-policy'
    | '/_auth/iam/(roles)/create-role'
    | '/_auth/iam/(users)/create-user'
    | '/_auth/s3/(buckets)/create-bucket'
    | '/_auth/s3/ls/'
    | '/_auth/ec2/(elastic-ips)/describe-addresses/$id'
    | '/_auth/ec2/(images)/describe-images/$id'
    | '/_auth/ec2/(instances)/describe-instances/$id'
    | '/_auth/ec2/(internet-gateways)/describe-internet-gateways/$id'
    | '/_auth/ec2/(key)/describe-key-pairs/$id'
    | '/_auth/ec2/(load-balancers)/describe-load-balancers/$id'
    | '/_auth/ec2/(nat-gateways)/describe-nat-gateways/$id'
    | '/_auth/ec2/(placement-groups)/describe-placement-groups/$id'
    | '/_auth/ec2/(route-tables)/describe-route-tables/$id'
    | '/_auth/ec2/(security-groups)/describe-security-groups/$id'
    | '/_auth/ec2/(snapshots)/describe-snapshots/$id'
    | '/_auth/ec2/(subnet)/describe-subnets/$id'
    | '/_auth/ec2/(target-groups)/describe-target-groups/$id'
    | '/_auth/ec2/(volumes)/describe-volumes/$id'
    | '/_auth/ec2/(volumes)/modify-volume/$id'
    | '/_auth/ec2/(vpc)/describe-vpcs/$id'
    | '/_auth/ecr/(repositories)/list-repositories/$id'
    | '/_auth/ecs/(clusters)/list-clusters/$clusterName'
    | '/_auth/eks/(clusters)/list-clusters/$clusterName'
    | '/_auth/iam/(instance-profiles)/list-instance-profiles/$instanceProfileName'
    | '/_auth/iam/(policies)/list-policies/$policyArn'
    | '/_auth/iam/(roles)/list-roles/$roleName'
    | '/_auth/iam/(users)/list-users/$userName'
    | '/_auth/s3/ls/$bucket/$'
    | '/_auth/ec2/(elastic-ips)/describe-addresses/'
    | '/_auth/ec2/(images)/describe-images/'
    | '/_auth/ec2/(instances)/describe-instances/'
    | '/_auth/ec2/(internet-gateways)/describe-internet-gateways/'
    | '/_auth/ec2/(key)/describe-key-pairs/'
    | '/_auth/ec2/(load-balancers)/describe-load-balancers/'
    | '/_auth/ec2/(nat-gateways)/describe-nat-gateways/'
    | '/_auth/ec2/(placement-groups)/describe-placement-groups/'
    | '/_auth/ec2/(route-tables)/describe-route-tables/'
    | '/_auth/ec2/(security-groups)/describe-security-groups/'
    | '/_auth/ec2/(snapshots)/describe-snapshots/'
    | '/_auth/ec2/(subnet)/describe-subnets/'
    | '/_auth/ec2/(target-groups)/describe-target-groups/'
    | '/_auth/ec2/(volumes)/describe-volumes/'
    | '/_auth/ec2/(vpc)/describe-vpcs/'
    | '/_auth/ecr/(repositories)/list-repositories/'
    | '/_auth/ecs/(clusters)/list-clusters/'
    | '/_auth/eks/(clusters)/list-clusters/'
    | '/_auth/iam/(instance-profiles)/list-instance-profiles/'
    | '/_auth/iam/(policies)/list-policies/'
    | '/_auth/iam/(roles)/list-roles/'
    | '/_auth/iam/(users)/list-users/'
    | '/_auth/s3/ls/$bucket/'
    | '/_auth/ecs/(clusters)/list-clusters/$clusterName_/services/$serviceName'
    | '/_auth/ecs/(clusters)/list-clusters/$clusterName_/tasks/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/nodes': {
      id: '/_auth/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof AuthNodesRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/s3/service-metrics': {
      id: '/_auth/s3/service-metrics'
      path: '/s3/service-metrics'
      fullPath: '/s3/service-metrics'
      preLoaderRoute: typeof AuthS3ServiceMetricsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/s3/ls/': {
      id: '/_auth/s3/ls/'
      path: '/s3/ls'
      fullPath: '/s3/ls/'
      preLoaderRoute: typeof AuthS3LsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/s3/(buckets)/create-bucket': {
      id: '/_auth/s3/(buckets)/create-bucket'
      path: '/s3/create-bucket'
      fullPath: '/s3/create-bucket'
      preLoaderRoute: typeof AuthS3bucketsCreateBucketRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/iam/(users)/create-user': {
      id: '/_auth/iam/(users)/create-user'
      path: '/iam/create-user'
      fullPath: '/iam/create-user'
      preLoaderRoute: typeof AuthIamusersCreateUserRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/iam/(roles)/create-role': {
      id: '/_auth/iam/(roles)/create-role'
      path: '/iam/create-role'
      fullPath: '/iam/create-role'
      preLoaderRoute: typeof AuthIamrolesCreateRoleRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/iam/(policies)/create-policy': {
      id: '/_auth/iam/(policies)/create-policy'
      path: '/iam/create-policy'
      fullPath: '/iam/create-policy'
      preLoaderRoute: typeof AuthIampoliciesCreatePolicyRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/iam/(instance-profiles)/create-instance-profile': {
      id: '/_auth/iam/(instance-profiles)/create-instance-profile'
      path: '/iam/create-instance-profile'
      fullPath: '/iam/create-instance-profile'
      preLoaderRoute: typeof AuthIaminstanceProfilesCreateInstanceProfileRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/eks/(clusters)/create-cluster': {
      id: '/_auth/eks/(clusters)/create-cluster'
      path: '/eks/create-cluster'
      fullPath: '/eks/create-cluster'
      preLoaderRoute: typeof AuthEksclustersCreateClusterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ecs/(clusters)/task-definitions': {
      id: '/_auth/ecs/(clusters)/task-definitions'
      path: '/ecs/task-definitions'
      fullPath: '/ecs/task-definitions'
      preLoaderRoute: typeof AuthEcsclustersTaskDefinitionsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ecs/(clusters)/run-task': {
      id: '/_auth/ecs/(clusters)/run-task'
      path: '/ecs/run-task'
      fullPath: '/ecs/run-task'
      preLoaderRoute: typeof AuthEcsclustersRunTaskRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ecs/(clusters)/register-task-definition': {
      id: '/_auth/ecs/(clusters)/register-task-definition'
      path: '/ecs/register-task-definition'
      fullPath: '/ecs/register-task-definition'
      preLoaderRoute: typeof AuthEcsclustersRegisterTaskDefinitionRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ecs/(clusters)/create-service': {
      id: '/_auth/ecs/(clusters)/create-service'
      path: '/ecs/create-service'
      fullPath: '/ecs/create-service'
      preLoaderRoute: typeof AuthEcsclustersCreateServiceRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(vpc)/create-vpc': {
      id: '/_auth/ec2/(vpc)/create-vpc'
      path: '/ec2/create-vpc'
      fullPath: '/ec2/create-vpc'
      preLoaderRoute: typeof AuthEc2vpcCreateVpcRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(volumes)/create-volume': {
      id: '/_auth/ec2/(volumes)/create-volume'
      path: '/ec2/create-volume'
      fullPath: '/ec2/create-volume'
      preLoaderRoute: typeof AuthEc2volumesCreateVolumeRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(target-groups)/create-target-group': {
      id: '/_auth/ec2/(target-groups)/create-target-group'
      path: '/ec2/create-target-group'
      fullPath: '/ec2/create-target-group'
      preLoaderRoute: typeof AuthEc2targetGroupsCreateTargetGroupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(subnet)/create-subnet': {
      id: '/_auth/ec2/(subnet)/create-subnet'
      path: '/ec2/create-subnet'
      fullPath: '/ec2/create-subnet'
      preLoaderRoute: typeof AuthEc2subnetCreateSubnetRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(snapshots)/create-snapshot': {
      id: '/_auth/ec2/(snapshots)/create-snapshot'
      path: '/ec2/create-snapshot'
      fullPath: '/ec2/create-snapshot'
      preLoaderRoute: typeof AuthEc2snapshotsCreateSnapshotRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(security-groups)/create-security-group': {
      id: '/_auth/ec2/(security-groups)/create-security-group'
      path: '/ec2/create-security-group'
      fullPath: '/ec2/create-security-group'
      preLoaderRoute: typeof AuthEc2securityGroupsCreateSecurityGroupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(route-tables)/create-route-table': {
      id: '/_auth/ec2/(route-tables)/create-route-table'
      path: '/ec2/create-route-table'
      fullPath: '/ec2/create-route-table'
      preLoaderRoute: typeof AuthEc2routeTablesCreateRouteTableRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(placement-groups)/create-placement-group': {
      id: '/_auth/ec2/(placement-groups)/create-placement-group'
      path: '/ec2/create-placement-group'
      fullPath: '/ec2/create-placement-group'
      preLoaderRoute: typeof AuthEc2placementGroupsCreatePlacementGroupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(nat-gateways)/create-nat-gateway': {
      id: '/_auth/ec2/(nat-gateways)/create-nat-gateway'
      path: '/ec2/create-nat-gateway'
      fullPath: '/ec2/create-nat-gateway'
      preLoaderRoute: typeof AuthEc2natGatewaysCreateNatGatewayRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(load-balancers)/create-load-balancer': {
      id: '/_auth/ec2/(load-balancers)/create-load-balancer'
      path: '/ec2/create-load-balancer'
      fullPath: '/ec2/create-load-balancer'
      preLoaderRoute: typeof AuthEc2loadBalancersCreateLoadBalancerRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(key)/import-key-pair': {
      id: '/_auth/ec2/(key)/import-key-pair'
      path: '/ec2/import-key-pair'
      fullPath: '/ec2/import-key-pair'
      preLoaderRoute: typeof AuthEc2keyImportKeyPairRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(key)/create-key-pair': {
      id: '/_auth/ec2/(key)/create-key-pair'
      path: '/ec2/create-key-pair'
      fullPath: '/ec2/create-key-pair'
      preLoaderRoute: typeof AuthEc2keyCreateKeyPairRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(internet-gateways)/create-internet-gateway': {
      id: '/_auth/ec2/(internet-gateways)/create-internet-gateway'
      path: '/ec2/create-internet-gateway'
      fullPath: '/ec2/create-internet-gateway'
      preLoaderRoute: typeof AuthEc2internetGatewaysCreateInternetGatewayRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(instances)/run-instances': {
      id: '/_auth/ec2/(instances)/run-instances'
      path: '/ec2/run-instances'
      fullPath: '/ec2/run-instances'
      preLoaderRoute: typeof AuthEc2instancesRunInstancesRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(elastic-ips)/allocate-address': {
      id: '/_auth/ec2/(elastic-ips)/allocate-address'
      path: '/ec2/allocate-address'
      fullPath: '/ec2/allocate-address'
      preLoaderRoute: typeof AuthEc2elasticIpsAllocateAddressRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/s3/ls/$bucket': {
      id: '/_auth/s3/ls/$bucket'
      path: '/s3/ls/$bucket'
      fullPath: '/s3/ls/$bucket'
      preLoaderRoute: typeof AuthS3LsBucketRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/s3/ls/$bucket/': {
      id: '/_auth/s3/ls/$bucket/'
      path: '/'
      fullPath: '/s3/ls/$bucket/'
      preLoaderRoute: typeof AuthS3LsBucketIndexRouteImport
      parentRoute: typeof AuthS3LsBucketRouteRoute
    }
    '/_auth/iam/(users)/list-users/': {
      id: '/_auth/iam/(users)/list-users/'
      path: '/iam/list-users'
      fullPath: '/iam/list-users/'
      preLoaderRoute: typeof AuthIamusersListUsersIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/iam/(roles)/list-roles/': {
      id: '/_auth/iam/(roles)/list-roles/'
      path: '/iam/list-roles'
      fullPath: '/iam/list-roles/'
      preLoaderRoute: typeof AuthIamrolesListRolesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/iam/(policies)/list-policies/': {
      id: '/_auth/iam/(policies)/list-policies/'
      path: '/iam/list-policies'
      fullPath: '/iam/list-policies/'
      preLoaderRoute: typeof AuthIampoliciesListPoliciesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/iam/(instance-profiles)/list-instance-profiles/': {
      id: '/_auth/iam/(instance-profiles)/list-instance-profiles/'
      path: '/iam/list-instance-profiles'
      fullPath: '/iam/list-instance-profiles/'
      preLoaderRoute: typeof AuthIaminstanceProfilesListInstanceProfilesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/eks/(clusters)/list-clusters/': {
      id: '/_auth/eks/(clusters)/list-clusters/'
      path: '/eks/list-clusters'
      fullPath: '/eks/list-clusters/'
      preLoaderRoute: typeof AuthEksclustersListClustersIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ecs/(clusters)/list-clusters/': {
      id: '/_auth/ecs/(clusters)/list-clusters/'
      path: '/ecs/list-clusters'
      fullPath: '/ecs/list-clusters/'
      preLoaderRoute: typeof AuthEcsclustersListClustersIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ecr/(repositories)/list-repositories/': {
      id: '/_auth/ecr/(repositories)/list-repositories/'
      path: '/ecr/list-repositories'
      fullPath: '/ecr/list-repositories/'
      preLoaderRoute: typeof AuthEcrrepositoriesListRepositoriesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(vpc)/describe-vpcs/': {
      id: '/_auth/ec2/(vpc)/describe-vpcs/'
      path: '/ec2/describe-vpcs'
      fullPath: '/ec2/describe-vpcs/'
      preLoaderRoute: typeof AuthEc2vpcDescribeVpcsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(volumes)/describe-volumes/': {
      id: '/_auth/ec2/(volumes)/describe-volumes/'
      path: '/ec2/describe-volumes'
      fullPath: '/ec2/describe-volumes/'
      preLoaderRoute: typeof AuthEc2volumesDescribeVolumesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(target-groups)/describe-target-groups/': {
      id: '/_auth/ec2/(target-groups)/describe-target-groups/'
      path: '/ec2/describe-target-groups'
      fullPath: '/ec2/describe-target-groups/'
      preLoaderRoute: typeof AuthEc2targetGroupsDescribeTargetGroupsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(subnet)/describe-subnets/': {
      id: '/_auth/ec2/(subnet)/describe-subnets/'
      path: '/ec2/describe-subnets'
      fullPath: '/ec2/describe-subnets/'
      preLoaderRoute: typeof AuthEc2subnetDescribeSubnetsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(snapshots)/describe-snapshots/': {
      id: '/_auth/ec2/(snapshots)/describe-snapshots/'
      path: '/ec2/describe-snapshots'
      fullPath: '/ec2/describe-snapshots/'
      preLoaderRoute: typeof AuthEc2snapshotsDescribeSnapshotsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(security-groups)/describe-security-groups/': {
      id: '/_auth/ec2/(security-groups)/describe-security-groups/'
      path: '/ec2/describe-security-groups'
      fullPath: '/ec2/describe-security-groups/'
      preLoaderRoute: typeof AuthEc2securityGroupsDescribeSecurityGroupsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(route-tables)/describe-route-tables/': {
      id: '/_auth/ec2/(route-tables)/describe-route-tables/'
      path: '/ec2/describe-route-tables'
      fullPath: '/ec2/describe-route-tables/'
      preLoaderRoute: typeof AuthEc2routeTablesDescribeRouteTablesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(placement-groups)/describe-placement-groups/': {
      id: '/_auth/ec2/(placement-groups)/describe-placement-groups/'
      path: '/ec2/describe-placement-groups'
      fullPath: '/ec2/describe-placement-groups/'
      preLoaderRoute: typeof AuthEc2placementGroupsDescribePlacementGroupsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(nat-gateways)/describe-nat-gateways/': {
      id: '/_auth/ec2/(nat-gateways)/describe-nat-gateways/'
      path: '/ec2/describe-nat-gateways'
      fullPath: '/ec2/describe-nat-gateways/'
      preLoaderRoute: typeof AuthEc2natGatewaysDescribeNatGatewaysIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(load-balancers)/describe-load-balancers/': {
      id: '/_auth/ec2/(load-balancers)/describe-load-balancers/'
      path: '/ec2/describe-load-balancers'
      fullPath: '/ec2/describe-load-balancers/'
      preLoaderRoute: typeof AuthEc2loadBalancersDescribeLoadBalancersIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(key)/describe-key-pairs/': {
      id: '/_auth/ec2/(key)/describe-key-pairs/'
      path: '/ec2/describe-key-pairs'
      fullPath: '/ec2/describe-key-pairs/'
      preLoaderRoute: typeof AuthEc2keyDescribeKeyPairsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(internet-gateways)/describe-internet-gateways/': {
      id: '/_auth/ec2/(internet-gateways)/describe-internet-gateways/'
      path: '/ec2/describe-internet-gateways'
      fullPath: '/ec2/describe-internet-gateways/'
      preLoaderRoute: typeof AuthEc2internetGatewaysDescribeInternetGatewaysIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(instances)/describe-instances/': {
      id: '/_auth/ec2/(instances)/describe-instances/'
      path: '/ec2/describe-instances'
      fullPath: '/ec2/describe-instances/'
      preLoaderRoute: typeof AuthEc2instancesDescribeInstancesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(images)/describe-images/': {
      id: '/_auth/ec2/(images)/describe-images/'
      path: '/ec2/describe-images'
      fullPath: '/ec2/describe-images/'
      preLoaderRoute: typeof AuthEc2imagesDescribeImagesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(elastic-ips)/describe-addresses/': {
      id: '/_auth/ec2/(elastic-ips)/describe-addresses/'
      path: '/ec2/describe-addresses'
      fullPath: '/ec2/describe-addresses/'
      preLoaderRoute: typeof AuthEc2elasticIpsDescribeAddressesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/s3/ls/$bucket/$': {
      id: '/_auth/s3/ls/$bucket/$'
      path: '/$'
      fullPath: '/s3/ls/$bucket/$'
      preLoaderRoute: typeof AuthS3LsBucketSplatRouteImport
      parentRoute: typeof AuthS3LsBucketRouteRoute
    }
    '/_auth/iam/(users)/list-users/$userName': {
      id: '/_auth/iam/(users)/list-users/$userName'
      path: '/iam/list-users/$userName'
      fullPath: '/iam/list-users/$userName'
      preLoaderRoute: typeof AuthIamusersListUsersUserNameRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/iam/(roles)/list-roles/$roleName': {
      id: '/_auth/iam/(roles)/list-roles/$roleName'
      path: '/iam/list-roles/$roleName'
      fullPath: '/iam/list-roles/$roleName'
      preLoaderRoute: typeof AuthIamrolesListRolesRoleNameRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/iam/(policies)/list-policies/$policyArn': {
      id: '/_auth/iam/(policies)/list-policies/$policyArn'
      path: '/iam/list-policies/$policyArn'
      fullPath: '/iam/list-policies/$policyArn'
      preLoaderRoute: typeof AuthIampoliciesListPoliciesPolicyArnRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/iam/(instance-profiles)/list-instance-profiles/$instanceProfileName': {
      id: '/_auth/iam/(instance-profiles)/list-instance-profiles/$instanceProfileName'
      path: '/iam/list-instance-profiles/$instanceProfileName'
      fullPath: '/iam/list-instance-profiles/$instanceProfileName'
      preLoaderRoute: typeof AuthIaminstanceProfilesListInstanceProfilesInstanceProfileNameRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/eks/(clusters)/list-clusters/$clusterName': {
      id: '/_auth/eks/(clusters)/list-clusters/$clusterName'
      path: '/eks/list-clusters/$clusterName'
      fullPath: '/eks/list-clusters/$clusterName'
      preLoaderRoute: typeof AuthEksclustersListClustersClusterNameRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ecs/(clusters)/list-clusters/$clusterName': {
      id: '/_auth/ecs/(clusters)/list-clusters/$clusterName'
      path: '/ecs/list-clusters/$clusterName'
      fullPath: '/ecs/list-clusters/$clusterName'
      preLoaderRoute: typeof AuthEcsclustersListClustersClusterNameRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ecr/(repositories)/list-repositories/$id': {
      id: '/_auth/ecr/(repositories)/list-repositories/$id'
      path: '/ecr/list-repositories/$id'
      fullPath: '/ecr/list-repositories/$id'
      preLoaderRoute: typeof AuthEcrrepositoriesListRepositoriesIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(vpc)/describe-vpcs/$id': {
      id: '/_auth/ec2/(vpc)/describe-vpcs/$id'
      path: '/ec2/describe-vpcs/$id'
      fullPath: '/ec2/describe-vpcs/$id'
      preLoaderRoute: typeof AuthEc2vpcDescribeVpcsIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(volumes)/modify-volume/$id': {
      id: '/_auth/ec2/(volumes)/modify-volume/$id'
      path: '/ec2/modify-volume/$id'
      fullPath: '/ec2/modify-volume/$id'
      preLoaderRoute: typeof AuthEc2volumesModifyVolumeIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(volumes)/describe-volumes/$id': {
      id: '/_auth/ec2/(volumes)/describe-volumes/$id'
      path: '/ec2/describe-volumes/$id'
      fullPath: '/ec2/describe-volumes/$id'
      preLoaderRoute: typeof AuthEc2volumesDescribeVolumesIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(target-groups)/describe-target-groups/$id': {
      id: '/_auth/ec2/(target-groups)/describe-target-groups/$id'
      path: '/ec2/describe-target-groups/$id'
      fullPath: '/ec2/describe-target-groups/$id'
      preLoaderRoute: typeof AuthEc2targetGroupsDescribeTargetGroupsIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(subnet)/describe-subnets/$id': {
      id: '/_auth/ec2/(subnet)/describe-subnets/$id'
      path: '/ec2/describe-subnets/$id'
      fullPath: '/ec2/describe-subnets/$id'
      preLoaderRoute: typeof AuthEc2subnetDescribeSubnetsIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(snapshots)/describe-snapshots/$id': {
      id: '/_auth/ec2/(snapshots)/describe-snapshots/$id'
      path: '/ec2/describe-snapshots/$id'
      fullPath: '/ec2/describe-snapshots/$id'
      preLoaderRoute: typeof AuthEc2snapshotsDescribeSnapshotsIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(security-groups)/describe-security-groups/$id': {
      id: '/_auth/ec2/(security-groups)/describe-security-groups/$id'
      path: '/ec2/describe-security-groups/$id'
      fullPath: '/ec2/describe-security-groups/$id'
      preLoaderRoute: typeof AuthEc2securityGroupsDescribeSecurityGroupsIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(route-tables)/describe-route-tables/$id': {
      id: '/_auth/ec2/(route-tables)/describe-route-tables/$id'
      path: '/ec2/describe-route-tables/$id'
      fullPath: '/ec2/describe-route-tables/$id'
      preLoaderRoute: typeof AuthEc2routeTablesDescribeRouteTablesIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(placement-groups)/describe-placement-groups/$id': {
      id: '/_auth/ec2/(placement-groups)/describe-placement-groups/$id'
      path: '/ec2/describe-placement-groups/$id'
      fullPath: '/ec2/describe-placement-groups/$id'
      preLoaderRoute: typeof AuthEc2placementGroupsDescribePlacementGroupsIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(nat-gateways)/describe-nat-gateways/$id': {
      id: '/_auth/ec2/(nat-gateways)/describe-nat-gateways/$id'
      path: '/ec2/describe-nat-gateways/$id'
      fullPath: '/ec2/describe-nat-gateways/$id'
      preLoaderRoute: typeof AuthEc2natGatewaysDescribeNatGatewaysIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(load-balancers)/describe-load-balancers/$id': {
      id: '/_auth/ec2/(load-balancers)/describe-load-balancers/$id'
      path: '/ec2/describe-load-balancers/$id'
      fullPath: '/ec2/describe-load-balancers/$id'
      preLoaderRoute: typeof AuthEc2loadBalancersDescribeLoadBalancersIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(key)/describe-key-pairs/$id': {
      id: '/_auth/ec2/(key)/describe-key-pairs/$id'
      path: '/ec2/describe-key-pairs/$id'
      fullPath: '/ec2/describe-key-pairs/$id'
      preLoaderRoute: typeof AuthEc2keyDescribeKeyPairsIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(internet-gateways)/describe-internet-gateways/$id': {
      id: '/_auth/ec2/(internet-gateways)/describe-internet-gateways/$id'
      path: '/ec2/describe-internet-gateways/$id'
      fullPath: '/ec2/describe-internet-gateways/$id'
      preLoaderRoute: typeof AuthEc2internetGatewaysDescribeInternetGatewaysIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(instances)/describe-instances/$id': {
      id: '/_auth/ec2/(instances)/describe-instances/$id'
      path: '/ec2/describe-instances/$id'
      fullPath: '/ec2/describe-instances/$id'
      preLoaderRoute: typeof AuthEc2instancesDescribeInstancesIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(images)/describe-images/$id': {
      id: '/_auth/ec2/(images)/describe-images/$id'
      path: '/ec2/describe-images/$id'
      fullPath: '/ec2/describe-images/$id'
      preLoaderRoute: typeof AuthEc2imagesDescribeImagesIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ec2/(elastic-ips)/describe-addresses/$id': {
      id: '/_auth/ec2/(elastic-ips)/describe-addresses/$id'
      path: '/ec2/describe-addresses/$id'
      fullPath: '/ec2/describe-addresses/$id'
      preLoaderRoute: typeof AuthEc2elasticIpsDescribeAddressesIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ecs/(clusters)/list-clusters/$clusterName_/tasks/$taskId': {
      id: '/_auth/ecs/(clusters)/list-clusters/$clusterName_/tasks/$taskId'
      path: '/ecs/list-clusters/$clusterName/tasks/$taskId'
      fullPath: '/ecs/list-clusters/$clusterName/tasks/$taskId'
      preLoaderRoute: typeof AuthEcsclustersListClustersClusterNameTasksTaskIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/ecs/(clusters)/list-clusters/$clusterName_/services/$serviceName': {
      id: '/_auth/ecs/(clusters)/list-clusters/$clusterName_/services/$serviceName'
      path: '/ecs/list-clusters/$clusterName/services/$serviceName'
      fullPath: '/ecs/list-clusters/$clusterName/services/$serviceName'
      preLoaderRoute: typeof AuthEcsclustersListClustersClusterNameServicesServiceNameRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthS3LsBucketRouteRouteChildren {
  AuthS3LsBucketSplatRoute: typeof AuthS3LsBucketSplatRoute
  AuthS3LsBucketIndexRoute: typeof AuthS3LsBucketIndexRoute
}

const AuthS3LsBucketRouteRouteChildren: AuthS3LsBucketRouteRouteChildren = {
  AuthS3LsBucketSplatRoute: AuthS3LsBucketSplatRoute,
  AuthS3LsBucketIndexRoute: AuthS3LsBucketIndexRoute,
}

const AuthS3LsBucketRouteRouteWithChildren =
  AuthS3LsBucketRouteRoute._addFileChildren(AuthS3LsBucketRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthNodesRoute: typeof AuthNodesRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthS3ServiceMetricsRoute: typeof AuthS3ServiceMetricsRoute
  AuthS3LsBucketRouteRoute: typeof AuthS3LsBucketRouteRouteWithChildren
  AuthEc2elasticIpsAllocateAddressRoute: typeof AuthEc2elasticIpsAllocateAddressRoute
  AuthEc2instancesRunInstancesRoute: typeof AuthEc2instancesRunInstancesRoute
  AuthEc2internetGatewaysCreateInternetGatewayRoute: typeof AuthEc2internetGatewaysCreateInternetGatewayRoute
  AuthEc2keyCreateKeyPairRoute: typeof AuthEc2keyCreateKeyPairRoute
  AuthEc2keyImportKeyPairRoute: typeof AuthEc2keyImportKeyPairRoute
  AuthEc2loadBalancersCreateLoadBalancerRoute: typeof AuthEc2loadBalancersCreateLoadBalancerRoute
  AuthEc2natGatewaysCreateNatGatewayRoute: typeof AuthEc2natGatewaysCreateNatGatewayRoute
  AuthEc2placementGroupsCreatePlacementGroupRoute: typeof AuthEc2placementGroupsCreatePlacementGroupRoute
  AuthEc2routeTablesCreateRouteTableRoute: typeof AuthEc2routeTablesCreateRouteTableRoute
  AuthEc2securityGroupsCreateSecurityGroupRoute: typeof AuthEc2securityGroupsCreateSecurityGroupRoute
  AuthEc2snapshotsCreateSnapshotRoute: typeof AuthEc2snapshotsCreateSnapshotRoute
  AuthEc2subnetCreateSubnetRoute: typeof AuthEc2subnetCreateSubnetRoute
  AuthEc2targetGroupsCreateTargetGroupRoute: typeof AuthEc2targetGroupsCreateTargetGroupRoute
  AuthEc2volumesCreateVolumeRoute: typeof AuthEc2volumesCreateVolumeRoute
  AuthEc2vpcCreateVpcRoute: typeof AuthEc2vpcCreateVpcRoute
  AuthEcsclustersCreateServiceRoute: typeof AuthEcsclustersCreateServiceRoute
  AuthEcsclustersRegisterTaskDefinitionRoute: typeof AuthEcsclustersRegisterTaskDefinitionRoute
  AuthEcsclustersRunTaskRoute: typeof AuthEcsclustersRunTaskRoute
  AuthEcsclustersTaskDefinitionsRoute: typeof AuthEcsclustersTaskDefinitionsRoute
  AuthEksclustersCreateClusterRoute: typeof AuthEksclustersCreateClusterRoute
  AuthIaminstanceProfilesCreateInstanceProfileRoute: typeof AuthIaminstanceProfilesCreateInstanceProfileRoute
  AuthIampoliciesCreatePolicyRoute: typeof AuthIampoliciesCreatePolicyRoute
  AuthIamrolesCreateRoleRoute: typeof AuthIamrolesCreateRoleRoute
  AuthIamusersCreateUserRoute: typeof AuthIamusersCreateUserRoute
  AuthS3bucketsCreateBucketRoute: typeof AuthS3bucketsCreateBucketRoute
  AuthS3LsIndexRoute: typeof AuthS3LsIndexRoute
  AuthEc2elasticIpsDescribeAddressesIdRoute: typeof AuthEc2elasticIpsDescribeAddressesIdRoute
  AuthEc2imagesDescribeImagesIdRoute: typeof AuthEc2imagesDescribeImagesIdRoute
  AuthEc2instancesDescribeInstancesIdRoute: typeof AuthEc2instancesDescribeInstancesIdRoute
  AuthEc2internetGatewaysDescribeInternetGatewaysIdRoute: typeof AuthEc2internetGatewaysDescribeInternetGatewaysIdRoute
  AuthEc2keyDescribeKeyPairsIdRoute: typeof AuthEc2keyDescribeKeyPairsIdRoute
  AuthEc2loadBalancersDescribeLoadBalancersIdRoute: typeof AuthEc2loadBalancersDescribeLoadBalancersIdRoute
  AuthEc2natGatewaysDescribeNatGatewaysIdRoute: typeof AuthEc2natGatewaysDescribeNatGatewaysIdRoute
  AuthEc2placementGroupsDescribePlacementGroupsIdRoute: typeof AuthEc2placementGroupsDescribePlacementGroupsIdRoute
  AuthEc2routeTablesDescribeRouteTablesIdRoute: typeof AuthEc2routeTablesDescribeRouteTablesIdRoute
  AuthEc2securityGroupsDescribeSecurityGroupsIdRoute: typeof AuthEc2securityGroupsDescribeSecurityGroupsIdRoute
  AuthEc2snapshotsDescribeSnapshotsIdRoute: typeof AuthEc2snapshotsDescribeSnapshotsIdRoute
  AuthEc2subnetDescribeSubnetsIdRoute: typeof AuthEc2subnetDescribeSubnetsIdRoute
  AuthEc2targetGroupsDescribeTargetGroupsIdRoute: typeof AuthEc2targetGroupsDescribeTargetGroupsIdRoute
  AuthEc2volumesDescribeVolumesIdRoute: typeof AuthEc2volumesDescribeVolumesIdRoute
  AuthEc2volumesModifyVolumeIdRoute: typeof AuthEc2volumesModifyVolumeIdRoute
  AuthEc2vpcDescribeVpcsIdRoute: typeof AuthEc2vpcDescribeVpcsIdRoute
  AuthEcrrepositoriesListRepositoriesIdRoute: typeof AuthEcrrepositoriesListRepositoriesIdRoute
  AuthEcsclustersListClustersClusterNameRoute: typeof AuthEcsclustersListClustersClusterNameRoute
  AuthEksclustersListClustersClusterNameRoute: typeof AuthEksclustersListClustersClusterNameRoute
  AuthIaminstanceProfilesListInstanceProfilesInstanceProfileNameRoute: typeof AuthIaminstanceProfilesListInstanceProfilesInstanceProfileNameRoute
  AuthIampoliciesListPoliciesPolicyArnRoute: typeof AuthIampoliciesListPoliciesPolicyArnRoute
  AuthIamrolesListRolesRoleNameRoute: typeof AuthIamrolesListRolesRoleNameRoute
  AuthIamusersListUsersUserNameRoute: typeof AuthIamusersListUsersUserNameRoute
  AuthEc2elasticIpsDescribeAddressesIndexRoute: typeof AuthEc2elasticIpsDescribeAddressesIndexRoute
  AuthEc2imagesDescribeImagesIndexRoute: typeof AuthEc2imagesDescribeImagesIndexRoute
  AuthEc2instancesDescribeInstancesIndexRoute: typeof AuthEc2instancesDescribeInstancesIndexRoute
  AuthEc2internetGatewaysDescribeInternetGatewaysIndexRoute: typeof AuthEc2internetGatewaysDescribeInternetGatewaysIndexRoute
  AuthEc2keyDescribeKeyPairsIndexRoute: typeof AuthEc2keyDescribeKeyPairsIndexRoute
  AuthEc2loadBalancersDescribeLoadBalancersIndexRoute: typeof AuthEc2loadBalancersDescribeLoadBalancersIndexRoute
  AuthEc2natGatewaysDescribeNatGatewaysIndexRoute: typeof AuthEc2natGatewaysDescribeNatGatewaysIndexRoute
  AuthEc2placementGroupsDescribePlacementGroupsIndexRoute: typeof AuthEc2placementGroupsDescribePlacementGroupsIndexRoute
  AuthEc2routeTablesDescribeRouteTablesIndexRoute: typeof AuthEc2routeTablesDescribeRouteTablesIndexRoute
  AuthEc2securityGroupsDescribeSecurityGroupsIndexRoute: typeof AuthEc2securityGroupsDescribeSecurityGroupsIndexRoute
  AuthEc2snapshotsDescribeSnapshotsIndexRoute: typeof AuthEc2snapshotsDescribeSnapshotsIndexRoute
  AuthEc2subnetDescribeSubnetsIndexRoute: typeof AuthEc2subnetDescribeSubnetsIndexRoute
  AuthEc2targetGroupsDescribeTargetGroupsIndexRoute: typeof AuthEc2targetGroupsDescribeTargetGroupsIndexRoute
  AuthEc2volumesDescribeVolumesIndexRoute: typeof AuthEc2volumesDescribeVolumesIndexRoute
  AuthEc2vpcDescribeVpcsIndexRoute: typeof AuthEc2vpcDescribeVpcsIndexRoute
  AuthEcrrepositoriesListRepositoriesIndexRoute: typeof AuthEcrrepositoriesListRepositoriesIndexRoute
  AuthEcsclustersListClustersIndexRoute: typeof AuthEcsclustersListClustersIndexRoute
  AuthEksclustersListClustersIndexRoute: typeof AuthEksclustersListClustersIndexRoute
  AuthIaminstanceProfilesListInstanceProfilesIndexRoute: typeof AuthIaminstanceProfilesListInstanceProfilesIndexRoute
  AuthIampoliciesListPoliciesIndexRoute: typeof AuthIampoliciesListPoliciesIndexRoute
  AuthIamrolesListRolesIndexRoute: typeof AuthIamrolesListRolesIndexRoute
  AuthIamusersListUsersIndexRoute: typeof AuthIamusersListUsersIndexRoute
  AuthEcsclustersListClustersClusterNameServicesServiceNameRoute: typeof AuthEcsclustersListClustersClusterNameServicesServiceNameRoute
  AuthEcsclustersListClustersClusterNameTasksTaskIdRoute: typeof AuthEcsclustersListClustersClusterNameTasksTaskIdRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthNodesRoute: AuthNodesRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthS3ServiceMetricsRoute: AuthS3ServiceMetricsRoute,
  AuthS3LsBucketRouteRoute: AuthS3LsBucketRouteRouteWithChildren,
  AuthEc2elasticIpsAllocateAddressRoute: AuthEc2elasticIpsAllocateAddressRoute,
  AuthEc2instancesRunInstancesRoute: AuthEc2instancesRunInstancesRoute,
  AuthEc2internetGatewaysCreateInternetGatewayRoute:
    AuthEc2internetGatewaysCreateInternetGatewayRoute,
  AuthEc2keyCreateKeyPairRoute: AuthEc2keyCreateKeyPairRoute,
  AuthEc2keyImportKeyPairRoute: AuthEc2keyImportKeyPairRoute,
  AuthEc2loadBalancersCreateLoadBalancerRoute:
    AuthEc2loadBalancersCreateLoadBalancerRoute,
  AuthEc2natGatewaysCreateNatGatewayRoute:
    AuthEc2natGatewaysCreateNatGatewayRoute,
  AuthEc2placementGroupsCreatePlacementGroupRoute:
    AuthEc2placementGroupsCreatePlacementGroupRoute,
  AuthEc2routeTablesCreateRouteTableRoute:
    AuthEc2routeTablesCreateRouteTableRoute,
  AuthEc2securityGroupsCreateSecurityGroupRoute:
    AuthEc2securityGroupsCreateSecurityGroupRoute,
  AuthEc2snapshotsCreateSnapshotRoute: AuthEc2snapshotsCreateSnapshotRoute,
  AuthEc2subnetCreateSubnetRoute: AuthEc2subnetCreateSubnetRoute,
  AuthEc2targetGroupsCreateTargetGroupRoute:
    AuthEc2targetGroupsCreateTargetGroupRoute,
  AuthEc2volumesCreateVolumeRoute: AuthEc2volumesCreateVolumeRoute,
  AuthEc2vpcCreateVpcRoute: AuthEc2vpcCreateVpcRoute,
  AuthEcsclustersCreateServiceRoute: AuthEcsclustersCreateServiceRoute,
  AuthEcsclustersRegisterTaskDefinitionRoute:
    AuthEcsclustersRegisterTaskDefinitionRoute,
  AuthEcsclustersRunTaskRoute: AuthEcsclustersRunTaskRoute,
  AuthEcsclustersTaskDefinitionsRoute: AuthEcsclustersTaskDefinitionsRoute,
  AuthEksclustersCreateClusterRoute: AuthEksclustersCreateClusterRoute,
  AuthIaminstanceProfilesCreateInstanceProfileRoute:
    AuthIaminstanceProfilesCreateInstanceProfileRoute,
  AuthIampoliciesCreatePolicyRoute: AuthIampoliciesCreatePolicyRoute,
  AuthIamrolesCreateRoleRoute: AuthIamrolesCreateRoleRoute,
  AuthIamusersCreateUserRoute: AuthIamusersCreateUserRoute,
  AuthS3bucketsCreateBucketRoute: AuthS3bucketsCreateBucketRoute,
  AuthS3LsIndexRoute: AuthS3LsIndexRoute,
  AuthEc2elasticIpsDescribeAddressesIdRoute:
    AuthEc2elasticIpsDescribeAddressesIdRoute,
  AuthEc2imagesDescribeImagesIdRoute: AuthEc2imagesDescribeImagesIdRoute,
  AuthEc2instancesDescribeInstancesIdRoute:
    AuthEc2instancesDescribeInstancesIdRoute,
  AuthEc2internetGatewaysDescribeInternetGatewaysIdRoute:
    AuthEc2internetGatewaysDescribeInternetGatewaysIdRoute,
  AuthEc2keyDescribeKeyPairsIdRoute: AuthEc2keyDescribeKeyPairsIdRoute,
  AuthEc2loadBalancersDescribeLoadBalancersIdRoute:
    AuthEc2loadBalancersDescribeLoadBalancersIdRoute,
  AuthEc2natGatewaysDescribeNatGatewaysIdRoute:
    AuthEc2natGatewaysDescribeNatGatewaysIdRoute,
  AuthEc2placementGroupsDescribePlacementGroupsIdRoute:
    AuthEc2placementGroupsDescribePlacementGroupsIdRoute,
  AuthEc2routeTablesDescribeRouteTablesIdRoute:
    AuthEc2routeTablesDescribeRouteTablesIdRoute,
  AuthEc2securityGroupsDescribeSecurityGroupsIdRoute:
    AuthEc2securityGroupsDescribeSecurityGroupsIdRoute,
  AuthEc2snapshotsDescribeSnapshotsIdRoute:
    AuthEc2snapshotsDescribeSnapshotsIdRoute,
  AuthEc2subnetDescribeSubnetsIdRoute: AuthEc2subnetDescribeSubnetsIdRoute,
  AuthEc2targetGroupsDescribeTargetGroupsIdRoute:
    AuthEc2targetGroupsDescribeTargetGroupsIdRoute,
  AuthEc2volumesDescribeVolumesIdRoute: AuthEc2volumesDescribeVolumesIdRoute,
  AuthEc2volumesModifyVolumeIdRoute: AuthEc2volumesModifyVolumeIdRoute,
  AuthEc2vpcDescribeVpcsIdRoute: AuthEc2vpcDescribeVpcsIdRoute,
  AuthEcrrepositoriesListRepositoriesIdRoute:
    AuthEcrrepositoriesListRepositoriesIdRoute,
  AuthEcsclustersListClustersClusterNameRoute:
    AuthEcsclustersListClustersClusterNameRoute,
  AuthEksclustersListClustersClusterNameRoute:
    AuthEksclustersListClustersClusterNameRoute,
  AuthIaminstanceProfilesListInstanceProfilesInstanceProfileNameRoute:
    AuthIaminstanceProfilesListInstanceProfilesInstanceProfileNameRoute,
  AuthIampoliciesListPoliciesPolicyArnRoute:
    AuthIampoliciesListPoliciesPolicyArnRoute,
  AuthIamrolesListRolesRoleNameRoute: AuthIamrolesListRolesRoleNameRoute,
  AuthIamusersListUsersUserNameRoute: AuthIamusersListUsersUserNameRoute,
  AuthEc2elasticIpsDescribeAddressesIndexRoute:
    AuthEc2elasticIpsDescribeAddressesIndexRoute,
  AuthEc2imagesDescribeImagesIndexRoute: AuthEc2imagesDescribeImagesIndexRoute,
  AuthEc2instancesDescribeInstancesIndexRoute:
    AuthEc2instancesDescribeInstancesIndexRoute,
  AuthEc2internetGatewaysDescribeInternetGatewaysIndexRoute:
    AuthEc2internetGatewaysDescribeInternetGatewaysIndexRoute,
  AuthEc2keyDescribeKeyPairsIndexRoute: AuthEc2keyDescribeKeyPairsIndexRoute,
  AuthEc2loadBalancersDescribeLoadBalancersIndexRoute:
    AuthEc2loadBalancersDescribeLoadBalancersIndexRoute,
  AuthEc2natGatewaysDescribeNatGatewaysIndexRoute:
    AuthEc2natGatewaysDescribeNatGatewaysIndexRoute,
  AuthEc2placementGroupsDescribePlacementGroupsIndexRoute:
    AuthEc2placementGroupsDescribePlacementGroupsIndexRoute,
  AuthEc2routeTablesDescribeRouteTablesIndexRoute:
    AuthEc2routeTablesDescribeRouteTablesIndexRoute,
  AuthEc2securityGroupsDescribeSecurityGroupsIndexRoute:
    AuthEc2securityGroupsDescribeSecurityGroupsIndexRoute,
  AuthEc2snapshotsDescribeSnapshotsIndexRoute:
    AuthEc2snapshotsDescribeSnapshotsIndexRoute,
  AuthEc2subnetDescribeSubnetsIndexRoute:
    AuthEc2subnetDescribeSubnetsIndexRoute,
  AuthEc2targetGroupsDescribeTargetGroupsIndexRoute:
    AuthEc2targetGroupsDescribeTargetGroupsIndexRoute,
  AuthEc2volumesDescribeVolumesIndexRoute:
    AuthEc2volumesDescribeVolumesIndexRoute,
  AuthEc2vpcDescribeVpcsIndexRoute: AuthEc2vpcDescribeVpcsIndexRoute,
  AuthEcrrepositoriesListRepositoriesIndexRoute:
    AuthEcrrepositoriesListRepositoriesIndexRoute,
  AuthEcsclustersListClustersIndexRoute: AuthEcsclustersListClustersIndexRoute,
  AuthEksclustersListClustersIndexRoute: AuthEksclustersListClustersIndexRoute,
  AuthIaminstanceProfilesListInstanceProfilesIndexRoute:
    AuthIaminstanceProfilesListInstanceProfilesIndexRoute,
  AuthIampoliciesListPoliciesIndexRoute: AuthIampoliciesListPoliciesIndexRoute,
  AuthIamrolesListRolesIndexRoute: AuthIamrolesListRolesIndexRoute,
  AuthIamusersListUsersIndexRoute: AuthIamusersListUsersIndexRoute,
  AuthEcsclustersListClustersClusterNameServicesServiceNameRoute:
    AuthEcsclustersListClustersClusterNameServicesServiceNameRoute,
  AuthEcsclustersListClustersClusterNameTasksTaskIdRoute:
    AuthEcsclustersListClustersClusterNameTasksTaskIdRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
